---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: &app unpackerr
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: onepassword
  target:
    name: unpackerr-secret
    creationPolicy: Owner
    template:
      engineVersion: v2
      data:
        UN_RADARR_0_API_KEY: "{{ .RADARR_API_KEY }}"
        UN_SONARR_0_API_KEY: "{{ .SONARR_API_KEY }}"
        UN_WEBHOOK_0_URL: "{{ .UNPACKERR_DISCORD_WEBHOOK_URL }}"
  dataFrom:
    - extract:
        key: sonarr
    - extract:
        key: radarr
    - extract:
        key: unpackerr