---
# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/external-secrets.io/externalsecret_v1beta1.json
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: crowdsec
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: onepassword
  target:
    name: crowdsec-secret
    template:
      engineVersion: v2
      data:        
        # CrowdSec Central enrollment token
        enroll-key: "{{ .CROWDSEC_ENROLL_KEY }}"
        
        # OPNsense API credentials for reflector
        opnsense-api-key: "{{ .CROWDSEC_OPNSENSE_API_KEY }}"
        opnsense-api-secret: "{{ .CROWDSEC_OPNSENSE_API_SECRET }}"
  dataFrom:
    - extract:
        key: crowdsec
