---
# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/external-secrets.io/externalsecret_v1.json
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: alertmanager-secret
  namespace: observability
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: onepassword
  target:
    creationPolicy: Owner
  data:
    - secretKey: ALERTMANAGER_HEARTBEAT_URL
      remoteRef:
        key: alertmanager
        property: ALERTMANAGER_HEARTBEAT_URL
    - secretKey: ALERTMANAGER_PUSHOVER_TOKEN
      remoteRef:
        key: alertmanager
        property: ALERTMANAGER_PUSHOVER_TOKEN
    - secretKey: PUSHOVER_USER_KEY
      remoteRef:
        key: pushover
        property: PUSHOVER_USER_KEY
---
# yaml-language-server: $schema=https://homelab-schemas-epg.pages.dev/external-secrets.io/externalsecret_v1.json
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: vps-metrics
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: onepassword
  target:
    name: vps-metrics-secret
    creationPolicy: Owner
    template:
      data:
        # Prometheus
        PROMETHEUS_USER: "{{ .VPS_PROMETHEUS_USER_USERNAME }}"
        PROMETHEUS_PASS: "{{ .VPS_PROMETHEUS_USER_PASSWORD  }}"

  dataFrom:
    - extract:
        key: vps-wireguard