---
# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/external-secrets.io/externalsecret_v1.json
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: alertmanager-secret
  namespace: ceph-csi-rbd
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: onepassword
  target:
    creationPolicy: Owner
  data:
    - secretKey: ALERTMANAGER_HEARTBEAT_URL
      remoteRef:
        key: alertmanager
        property: heartbeat-url
    - secretKey: ALERTMANAGER_PUSHOVER_TOKEN
      remoteRef:
        key: alertmanager
        property: pushover-token
    - secretKey: PUSHOVER_USER_KEY
      remoteRef:
        key: alertmanager
        property: pushover-user-key