---
apiVersion: v1
kind: Service
metadata:
  name: prometheus-remote-write
  namespace: observability
  annotations:
    io.cilium/lb-ipam-ips: "10.0.30.91"
spec:
  type: LoadBalancer
  selector:
    app.kubernetes.io/name: prometheus
    prometheus: kube-prometheus-stack
  ports:
    - name: remote-write
      port: 9090
      targetPort: 9090
      protocol: TCP
