---
# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/external-secrets.io/externalsecret_v1beta1.json
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: trivy-server-secret
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: onepassword-connect
  target:
    name: trivy-server-secret
    creationPolicy: Owner
  data:
    - secretKey: token
      remoteRef:
        key: trivy-server
        property: TRIVY_SERVER_TOKEN
