---
# yaml-language-server: $schema=https://json.schemastore.org/kustomization
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ./externalsecret.yaml
  - ./garagecluster.yaml
  # P3: declarative buckets + keys on garage-operated
  - ./buckets.yaml
  - ./importkey-externalsecrets.yaml
  - ./keys.yaml
