---
# yaml-language-server: $schema=https://kochhaus-schemas.pages.dev/external-secrets.io/externalsecret_v1.json
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: newt
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: onepassword
  target:
    name: newt-secret
    creationPolicy: Owner
    template:
      engineVersion: v2
      data:
        PANGOLIN_ENDPOINT: "{{ .PANGOLIN_ENDPOINT }}"
        NEWT_SITE_ID: "{{ .PANGOLIN_NEWT_SITE_ID}}"
        NEWT_SITE_SECRET: "{{ .PANGOLIN_NEWT_SITE_SECRET}}"
  dataFrom:
    - extract:
        key: pangolin