---
# yaml-language-server: $schema=https://kochhaus-schemas.pages.dev/external-secrets.io/externalsecret_v1.json
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: pangolin-api
  namespace: newt
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: onepassword
  target:
    name: pangolin-api
    creationPolicy: Owner
    template:
      engineVersion: v2
      data:
        endpoint: "{{ .PANGOLIN_ENDPOINT }}"
        apiKey: "{{ .PANGOLIN_API_KEY }}"
  dataFrom:
    - extract:
        key: pangolin