apiVersion: v1
kind: PersistentVolume
metadata:
  name: cephfs-static-pv
  namespace: media
spec:
  accessModes:
  - ReadWriteMany
  capacity:
    storage: 1Gi
  csi:
    driver: cephfs.csi.ceph.com
    nodeStageSecretRef:
      # node stage secret name
      name: csi-cephfs-secret
      # node stage secret namespace where above secret is created
      namespace: ceph-csi-cephfs
    volumeAttributes:
      # optional file system to be mounted
      "fsName": "kube-fs"
      # Required options from storageclass parameters need to be added in volumeAttributes
      "clusterID": "2ec73f92-a0c8-11eb-b84d-eb70282a4edf"
      "staticVolume": "true"
      "rootPath": /volumes/testGroup/testSubVolume
    # volumeHandle can be anything, need not to be same
    # as PV name or volume name. keeping same for brevity
    volumeHandle: cephfs-static-pv
    storageclassName: csi-cephfs-sc
  persistentVolumeReclaimPolicy: Retain
  volumeMode: Filesystem