---
apiVersion: v1
kind: Pod
metadata:
  name: ceph-rbd-test-pod
  namespace: media
spec:
  containers:
    - name: fc-container
      image: fedora:43
      command: ["/bin/sh", "-c"]
      args: ["tail -f /dev/null"]
      volumeDevices:
        - name: data
          devicePath: /dev/xvda
  volumes:
    - name: data
      persistentVolumeClaim:
        claimName: rcsi-rbd-pvc
