---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: csi-cephfs-pvc
  namespace: media
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 1Gi
  storageclassName: csi-cephfs-sc
  volumeMode: Filesystem
  volumeName: cephfs-static-pv
