---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: csi-rbd-pvc
  namespace: media
spec:
  accessModes:
    - ReadWriteOnce
  volumeMode: Block
  resources:
    requests:
      storage: 2Gi
  storageClassName: csi-rbd-sc
