---
# yaml-language-server: $schema=https://json.schemastore.org/kustomization
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: media
components:
  - ../../components/common
resources:
  - ./plex/ks.yaml
  - ./flaresolverr/ks.yaml
  - ./prowlarr/ks.yaml
  - ./qbittorrent/ks.yaml
  - ./radarr/ks.yaml
  - ./sonarr/ks.yaml
  - ./recyclarr/ks.yaml
  - ./bazarr/ks.yaml
  - ./jellyseerr/ks.yaml
  - ./huntarr/ks.yaml
  - ./cleanuparr/ks.yaml
  - ./wizarr/ks.yaml
  - ./gluetun/ks.yaml
  - ./tautulli/ks.yaml
  - ./immich/ks.yaml
  - ./audiobookshelf/ks.yaml
  - ./readarr/ks.yaml
  - ./readarr-books/ks.yaml
  - ./sabnzbd/ks.yaml
  - ./autobrr/ks.yaml
  - ./cross-seed/ks.yaml
  - ./rreading-glasses/ks.yaml
  - ./audiobookrequest/ks.yaml
  - ./booklore/ks.yaml
  - ./recommendarr/ks.yaml
  - ./mydia/ks.yaml
  - ./qui/ks.yaml