---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: nas-media-pvc
  namespace: media
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 10Gi
  storageClassName: nfs-csi