apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: nas-media-pvc
  namespace: media
spec:
  accessModes:
    - ReadWriteMany
  storageClassName: nfs-k8s
  resources:
    requests:
      storage: 1Mi