---
creation_rules:
  - path_regex: talos/.*\.sops\.ya?ml
    mac_only_encrypted: true
    age: "age1am64psa3hmwqnc924p9vuphyp4txekclpsysx6fkqtktgzppgusqfah833"
  - path_regex: (bootstrap|kubernetes)/.*\.sops\.ya?ml
    encrypted_regex: "^(data|stringData)$"
    mac_only_encrypted: true
    age: "age1am64psa3hmwqnc924p9vuphyp4txekclpsysx6fkqtktgzppgusqfah833"
stores:
  yaml:
    indent: 2
