---
# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/external-secrets.io/externalsecret_v1.json
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: seerr
  namespace: media
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: onepassword
  target:
    name: seerr-secret
    template:
      engineVersion: v2
      data:
        API_KEY: "{{ .SEERR_API_KEY }}"

        # PostgreSQL database connection
        DATABASE_URL: "postgres://{{ .SEERR_POSTGRES_USER }}:{{ .SEERR_POSTGRES_PASS }}@{{ .POSTGRES_RW_SVC }}:5432/seerr?sslmode=disable"

        # Postgres Init (for init container)
        INIT_POSTGRES_DBNAME: seerr
        INIT_POSTGRES_HOST: "{{ .POSTGRES_RW_SVC }}"
        INIT_POSTGRES_PORT: "5432"
        INIT_POSTGRES_USER: "{{ .SEERR_POSTGRES_USER }}"
        INIT_POSTGRES_PASS: "{{ .SEERR_POSTGRES_PASS }}"
        INIT_POSTGRES_SUPER_PASS: "{{ .POSTGRES_SUPER_PASS }}"

        #Restic backup
        RESTIC_REPOSITORY: "/repository/seerr"
        RESTIC_PASSWORD: "{{ .RESTIC_PASSWORD }}"
  dataFrom:
    - extract:
        key: seerr
    - extract:
        key: restic
    - extract:
        key: cloudnative-pg