---
# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/external-secrets.io/externalsecret_v1.json
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: jotty
spec:
  refreshInterval: 5m
  secretStoreRef:
    kind: ClusterSecretStore
    name: onepassword
  target:
    name: jotty-secret
    creationPolicy: Owner
    template:
      data:
        # OIDC settings
        OIDC_ISSUER: "https://sso.${SECRET_DOMAIN}/application/o/jotty/"
        OIDC_CLIENT_ID: "{{ .JOTTY_OIDC_CLIENT_ID }}"
        OIDC_CLIENT_SECRET: "{{ .JOTTY_OIDC_CLIENT_SECRET }}"
        OIDC_LOGOUT_URL: "https://sso.${SECRET_DOMAIN}/application/o/jotty/end-session/"

  dataFrom:
    - extract:
        key: jotty
