---
# yaml-language-server: $schema=https://raw.githubusercontent.com/bjw-s/helm-charts/main/charts/other/app-template/schemas/helmrelease-helm-v2.schema.json
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: &app jotty
spec:
  interval: 1h
  chartRef:
    kind: OCIRepository
    name: app-template
    namespace: flux-system
  install:
    remediation:
      retries: 3
  upgrade:
    cleanupOnFail: true
    remediation:
      strategy: rollback
      retries: 3
  values:
    controllers:
      jotty:
        annotations:
          reloader.stakater.com/auto: "true"
        containers:
          app:
            image:
              repository: ghcr.io/fccview/jotty
              tag: 1.21.1@sha256:275c844be9aae5736ad4d120f554278be41a48e125af3782d3713a72aff9e264
            env:
              TZ: ${SECRET_TIMEZONE}
              NODE_ENV: production
              APP_URL: https://jotty.${SECRET_DOMAIN}
              SSO_MODE: oidc
              SSO_FALLBACK_LOCAL: no
              # OIDC_ADMIN_GROUPS: jotty-admins
              # OIDC_ADMIN_ROLES: admins
              # OIDC_GROUPS_SCOPE: oidc-groups
            envFrom:
              - secretRef:
                  name: jotty-secret
            securityContext:
              allowPrivilegeEscalation: false
              readOnlyRootFilesystem: false  # Changed to false as the app needs to write to cache
              capabilities: { drop: ["ALL"] }
            resources:
              requests:
                cpu: 15m
                memory: 105M
              limits:
                memory: 128M
        pod:
          securityContext:
            runAsUser: 1000
            runAsGroup: 1000
            runAsNonRoot: true
            fsGroup: 1000
            fsGroupChangePolicy: OnRootMismatch
    service:
      app:
        controller: jotty
        ports:
          http:
            port: &port 3000
    route:
      external:
        annotations:
          external-dns.alpha.kubernetes.io/target: external.${SECRET_DOMAIN}
        hostnames: ["{{ .Release.Name }}.${SECRET_DOMAIN}"]
        parentRefs:
          - name: external
            namespace: network
            sectionName: https
        rules:
          - backendRefs:
              - identifier: app
                port: *port
    persistence:
      data:
        existingClaim: *app
        advancedMounts:
          jotty:
            app:
              - path: /app/data
                readOnly: false
      config:
        existingClaim: jotty-config
        advancedMounts:
          jotty:
            app:
              - path: /app/config
                readOnly: false
      cache:
        enabled: true
        type: emptyDir
        sizeLimit: 1Gi
        advancedMounts:
          jotty:
            app:
              - path: /app/.next/cache
                readOnly: false
