---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: &app kitchenowl
  namespace: &ns default
  labels:
    substitution.flux.home.arpa/enabled: "true"
spec:
  targetNamespace: *ns
  commonMetadata:
    labels:
      app.kubernetes.io/name: *app
  path: ./kubernetes/apps/default/kitchenowl/app
  sourceRef:
    kind: GitRepository
    name: flux-system
    namespace: flux-system
  dependsOn:
    - name: ceph-csi-rbd
      namespace: ceph-csi-rbd
    - name: external-secrets
      namespace: external-secrets
  postBuild:
    substitute:
      APP: *app
      CEPH_RBD_CAPACITY: 2Gi
    substituteFrom:
      - name: cluster-secrets
        kind: Secret
  prune: true
  wait: true
  interval: 30m
  timeout: 5m
  components:
    - ../../../../components/gatus/external
    - ../../../../components/ceph-rbd