---
# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/external-secrets.io/externalsecret_v1.json
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: qbittorrent
  namespace: media
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: onepassword
  target:
    name: qbittorrent-secret
    template:
      data:
        GLUETUN_CONTROL_SERVER_API_KEY: "{{ .QB_GLUETUN_API_KEY }}"
        OPENVPN_USER: "{{ .PROTON_OPENVPN_USER }}+pmp"
        OPENVPN_PASSWORD: "{{ .PROTON_OPENVPN_PASS }}"
        # XSEED_APIKEY: "{{ .CROSS_SEED_API_KEY }}"

        #Restic backup
        RESTIC_REPOSITORY: "/repository/qbittorrent"
        RESTIC_PASSWORD: "{{ .RESTIC_PASSWORD }}"
  dataFrom:
    - extract:
        key: qbittorrent
    - extract:
        key: protonvpn
    - extract:
        key: restic
    # - extract:
    #     key: cross-seed
---
# yaml-language-server: $schema=https://raw.githubusercontent.com/datreeio/CRDs-catalog/main/external-secrets.io/externalsecret_v1.json
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: qbittorrent-gluetun
  namespace: media
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: onepassword
  target:
    name: qbittorrent-gluetun-secret
    template:
      data:
        auth.toml: |
          [[roles]]
          name = "gluetun-qb-port-sync"
          routes = [
            "GET /v1/publicip/ip",
            "GET /v1/openvpn/portforwarded",
            "GET /v1/portforward"
          ]
          auth = "apikey"
          apikey = "{{ .QB_GLUETUN_API_KEY }}"
  dataFrom:
    - extract:
        key: qbittorrent