---
apiVersion: volsync.backube/v1alpha1
kind: ReplicationDestination
metadata:
  name: qbittorrent-restore
  namespace: media
spec:
  trigger:
    manual: restore-20250724-180010
  restic:
    repository: qbittorrent-secret
    destinationPVC: qbittorrent
    storageClassName: csi-rbd-sc
    accessModes: [ReadWriteOnce]
    capacity: 2Gi
    moverSecurityContext:
      runAsUser: 1000
      runAsGroup: 1000
      fsGroup: 1000