---
# yaml-language-server: $schema=https://crd.movishell.pl/external-secrets.io/externalsecret_v1.json
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: hetzner-exporter
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: onepassword
  target:
    name: hetzner-exporter-secret
    deletionPolicy: Delete
    template:
      engineVersion: v2
      data:
        HETZNER_API_TOKEN: "{{ .HETZNER_API_TOKEN }}"
  dataFrom:
    - extract:
        key: hetzner
