---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ./externalsecret.yaml
  - ./helmrelease.yaml
  - ./prometheusrule.yaml
configMapGenerator:
  - name: hetzner-exporter-scripts
    files:
      - resources/run.sh
      - resources/storagebox.sh
      # add resources/vps.sh here later
generatorOptions:
  disableNameSuffixHash: true