---
apiVersion: flowcontrol.apiserver.k8s.io/v1
kind: FlowSchema
metadata:
  name: capacitor-elevated
spec:
  priorityLevelConfiguration:
    name: workload-high
  matchingPrecedence: 850
  distinguisherMethod:
    type: ByUser
  rules:
    - subjects:
        - kind: ServiceAccount
          serviceAccount:
            name: capacitor-next
            namespace: observability
        - kind: ServiceAccount
          serviceAccount:
            name: capacitor-next-preset-clusteradmin
            namespace: observability
      resourceRules:
        - verbs: ["*"]
          apiGroups: ["*"]
          resources: ["*"]
          clusterScope: true
          namespaces: ["*"]
