---
# yaml-language-server: $schema=https://raw.githubusercontent.com/fluxcd-community/flux2-schemas/main/kustomization-kustomize-v1.json
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: intel-device-plugins-operator
  namespace: flux-system
spec:
  path: ./kubernetes/apps/kube-system/intel-device-plugin/operator
  sourceRef:
    kind: GitRepository
    name: flux-system
    namespace: flux-system
  interval: 30m
  prune: false
  wait: true
  dependsOn:
    - name: cert-manager
      namespace: cert-manager
    - name: node-feature-discovery
---
# yaml-language-server: $schema=https://raw.githubusercontent.com/fluxcd-community/flux2-schemas/main/kustomization-kustomize-v1.json
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: intel-device-plugins-gpu
  namespace: flux-system
spec:
  path: ./kubernetes/apps/kube-system/intel-device-plugin/gpu
  sourceRef:
    kind: GitRepository
    name: flux-system
    namespace: flux-system
  interval: 30m
  prune: false
  wait: true
  dependsOn:
    - name: intel-device-plugins-operator
