---
# yaml-language-server: $schema=https://raw.githubusercontent.com/datreeio/CRDs-catalog/main/external-secrets.io/externalsecret_v1.json
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: versity
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: onepassword
  target:
    name: versity-secret
    template:
      engineVersion: v2
      data:
        AWS_ACCESS_KEY_ID: "{{ .VERSITY_ACCESS_KEY_ID }}"
        AWS_SECRET_ACCESS_KEY: "{{ .VERSITY_SECRET_ACCESS_KEY }}"
  dataFrom:
    - extract:
        key: versity