---
# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/helm.toolkit.fluxcd.io/helmrelease_v2.json
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: &app external-dns-adguard-home
  namespace: network
spec:
  interval: 30m
  chart:
    spec:
      chart: external-dns
      version: 1.19.0
      sourceRef:
        kind: HelmRepository
        name: external-dns
        namespace: flux-system
  install:
    crds: CreateReplace
    remediation:
      retries: -1
    timeout: 5m
  upgrade:
    cleanupOnFail: true
    crds: CreateReplace
    remediation:
      strategy: rollback
      retries: -1
    timeout: 5m
  values:
    # domainFilters: ["internal.${SECRET_DOMAIN}"]
    provider:
      name: webhook
      webhook:
        image:
          repository: ghcr.io/muhlba91/external-dns-provider-adguard
          tag: v11.0.0@sha256:7bc1d6b3d4590f8fbb6f8452d98aecb47b4ea0a19c09ce44a6f2f0a4c2b162d4
          pullPolicy: IfNotPresent
        env:
          - name: ADGUARD_URL
            value: https://adguard.${SECRET_DOMAIN}
          - name: &name ADGUARD_USER
            valueFrom:
              secretKeyRef:
                name: &secret external-dns-adguard-home
                namespace: network
                key: *name
          - name: &name ADGUARD_PASSWORD
            valueFrom:
              secretKeyRef:
                name: *secret
                key: *name
          - name: SERVER_HOST
            value: 0.0.0.0
        securityContext:
          readOnlyRootFilesystem: true
    interval: 1h
    triggerLoopOnEvent: true
    policy: sync
    registry: noop
    sources: ["ingress", "gateway-httproute"]
    extraArgs:
      - --webhook-provider-url=http://localhost:8888
      - --ingress-class=internal
      - --gateway-label-filter=dns-provider=internal
      - --annotation-filter=external-dns.alpha.kubernetes.io/exclude notin (true)
    podAnnotations:
      secret.reloader.stakater.com/reload: *secret
    logLevel: debug