---
# yaml-language-server: $schema=https://raw.githubusercontent.com/fluxcd-community/flux2-schemas/main/helmrelease-helm-v2.json
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: hajimari
spec:
  interval: 30m
  chart:
    spec:
      chart: hajimari
      version: 2.0.2
      sourceRef:
        kind: HelmRepository
        name: hajimari
        namespace: flux-system
  install:
    remediation:
      retries: 3
  upgrade:
    cleanupOnFail: true
    remediation:
      strategy: rollback
      retries: 3
  values:
    env:
      TZ: ${SECRET_TIMEZONE}
    hajimari:
      title: Apps
      darkTheme: espresso
      alwaysTargetBlank: true
      defaultEnable: true
      namespaceSelector:
        any: true
      name: Citizen
      defaultSearchProvider: DuckDuckGo
      showGlobalBookmarks: true
      globalBookmarks:
        - name: Communicate
          bookmarks:
            - name: Discord
              url: "https://discord.com/login"
        - name: mail
          bookmarks:
            - name: Gmail
              url: "https://gmail.com"
            - name: Fastmail
        - name: Media
          bookmarks:
            - name: Netflix
              url: "https://www.netflix.com/browse"
            - name: Disney+
              url: "https://www.disneyplus.com/login"
            - name: Plex
              url: "https://app.plex.tv/desktop"
            - name: YouTube
              url: "https://youtube.com/feed/subscriptions"
            - name: Amazon Prime
              url: "https://www.primevideo.com"
            - name: Spotify
              url: "https://open.spotify.com/browse"
            - name: QBittorrent
              url: "https://qbittorrent.cftollefsen.com"
    service:
      main:
        ipFamilyPolicy: SingleStack
    ingress:
      main:
        enabled: true
        ingressClassName: internal
        annotations:
          hajimari.io/enable: "false"
        hosts:
          - host: hajimari.${SECRET_DOMAIN}
            paths:
              - path: /
                pathType: Prefix
    podAnnotations:
      configmap.reloader.stakater.com/reload: "hajimari-settings"
    persistence:
      data:
        enabled: true
        type: emptyDir
    resources:
      requests:
        cpu: 50m
        memory: 128M