---
apiVersion: gateway.envoyproxy.io/v1alpha1
kind: EnvoyProxy
metadata:
  name: envoy-external-proxy
  namespace: network
spec:
  telemetry:
    tracing:
      samplingRate: 50  # Sample 50% of requests
      provider:
        type: OpenTelemetry
        host: tempo-distributor.observability.svc.cluster.local
        port: 4317
  provider:
    type: Kubernetes
    kubernetes:
      envoyDeployment:
        name: envoy-gateway-external
        replicas: 3
        pod:
          affinity:
            podAntiAffinity:
              preferredDuringSchedulingIgnoredDuringExecution:
                - weight: 100
                  podAffinityTerm:
                    labelSelector:
                      matchLabels:
                        gateway.envoyproxy.io/owning-gateway-name: external
                    topologyKey: kubernetes.io/hostname
      envoyService:
        name: envoy-gateway-external
        type: LoadBalancer
        externalTrafficPolicy: Local
        loadBalancerIP: "10.0.30.44"
        annotations:
          external-dns.alpha.kubernetes.io/hostname: "*.${SECRET_DOMAIN}"