---
apiVersion: gateway.networking.k8s.io/v1beta1
kind: ReferenceGrant
metadata:
  name: envoy-cert-manager-certs
  namespace: cert-manager
spec:
  from:
    - group: gateway.networking.k8s.io
      kind: Gateway
      namespace: network
  to:
    - group: ""
      kind: Secret
---
apiVersion: gateway.networking.k8s.io/v1beta1
kind: ReferenceGrant
metadata:
  name: envoy-authentik-auth
  namespace: security
spec:
  from:
    - group: gateway.envoyproxy.io
      kind: SecurityPolicy
      namespace: default
    - group: gateway.envoyproxy.io
      kind: SecurityPolicy
      namespace: media
    - group: gateway.envoyproxy.io
      kind: SecurityPolicy
      namespace: security
    - group: gateway.envoyproxy.io
      kind: SecurityPolicy
      namespace: observability
    - group: gateway.envoyproxy.io
      kind: SecurityPolicy
      namespace: database
  to:
    - group: ""
      kind: Service
      name: ak-outpost-authentik-embedded-outpost