---
# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/external-secrets.io/externalsecret_v1.json
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: sabnzbd
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: onepassword
  target:
    name: sabnzbd-secret
    template:
      data:
        CROSS_SEED_API_KEY: "{{ .CROSS_SEED_API_KEY }}"
        SABNZBD__API_KEY: &apiKey "{{ .SABNZBD_API_KEY }}"
        SABNZBD__NZB_KEY: *apiKey

        #Restic backup
        RESTIC_REPOSITORY: "/repository/sabnzbd"
        RESTIC_PASSWORD: "{{ .RESTIC_PASSWORD }}"
  dataFrom:
    - extract:
        key: cross-seed
    - extract:
        key: sabnzbd
    - extract:
        key: restic
---
# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/external-secrets.io/externalsecret_v1.json
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: sabnzbd-gluetun
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: onepassword
  target:
    name: sabnzbd-gluetun-secret
    creationPolicy: Owner
    template:
      engineVersion: v2
      data:
        GLUETUN_CONTROL_SERVER_API_KEY: "{{ .SABNZBD_GLUETUN_API_KEY }}"
        OPENVPN_USER: "{{ .PROTON_OPENVPN_USER }}+pmp"
        OPENVPN_PASSWORD: "{{ .PROTON_OPENVPN_PASS }}"
  dataFrom:
    - extract:
        key: sabnzbd
    - extract:
        key: protonvpn