---
# yaml-language-server: $schema=https://raw.githubusercontent.com/bjw-s-labs/helm-charts/main/charts/other/app-template/schemas/helmrelease-helm-v2.schema.json
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: &app sabnzbd
spec:
  interval: 1h
  chartRef:
    kind: OCIRepository
    name: app-template
    namespace: flux-system
  install:
    remediation:
      retries: -1
  upgrade:
    cleanupOnFail: true
    remediation:
      retries: 3
  values:
    controllers:
      sabnzbd:
        annotations:
          reloader.stakater.com/auto: "true"
        initContainers:
          coredns:
            image:
              repository: coredns/coredns
              tag: 1.13.1
            args: ["-conf", "/etc/coredns/Corefile"]
            restartPolicy: Always
            securityContext:
              capabilities:
                add: ["NET_BIND_SERVICE"]
              readOnlyRootFilesystem: false
          gluetun:
            dependsOn:
              - coredns
            image:
              repository: ghcr.io/qdm12/gluetun
              tag: v3.40.0@sha256:2b42bfa046757145a5155acece417b65b4443c8033fb88661a8e9dcf7fda5a00
            restartPolicy: Always
            env:
              DOT: "off"
              DNS_ADDRESS: 127.0.0.2
              DNS_KEEP_NAMESERVER: "on"
              HTTP_CONTROL_SERVER_ADDRESS: ":8000"
              HTTP_CONTROL_SERVER_API_KEY:
                valueFrom:
                  secretKeyRef:
                    name: sabnzbd-gluetun-secret
                    key: GLUETUN_CONTROL_SERVER_API_KEY
              VPN_SERVICE_PROVIDER: protonvpn
              VPN_TYPE: openvpn
              SERVER_COUNTRIES: Norway,Netherlands,Switzerland,Sweden,Denmark
              FIREWALL_INPUT_PORTS: "80,8000"
              FIREWALL_OUTBOUND_SUBNETS: 10.42.0.0/16,10.43.0.0/16
            envFrom:
              - secretRef:
                  name: sabnzbd-gluetun-secret
            securityContext:
              runAsUser: 0
              runAsGroup: 0
              runAsNonRoot: false
              capabilities: { add: ["NET_ADMIN"] }
              allowPrivilegeEscalation: true
            resources:
              limits:
                squat.ai/tun: "1"
        containers:
          app:
            image:
              repository: ghcr.io/home-operations/sabnzbd
              tag: 4.5.5@sha256:da57e01cdebc547852b6df85c8df8c0e4d87792742c7608c5590dc653b184e8c
            env:
              CROSS_SEED_HOST: cross-seed.media.svc.cluster.local
              SABNZBD__PORT: &port 80
              SABNZBD__HOST_WHITELIST_ENTRIES: >-
                sabnzbd,
                sabnzbd.default,
                sabnzbd.default.svc,
                sabnzbd.default.svc.cluster,
                sabnzbd.default.svc.cluster.local,
                sab.${SECRET_DOMAIN}
              TZ: ${SECRET_TIMEZONE}
            envFrom:
              - secretRef:
                  name: sabnzbd-secret
            probes:
              liveness: &probes
                enabled: true
                custom: true
                spec:
                  httpGet:
                    path: /api?mode=version
                    port: *port
                  initialDelaySeconds: 0
                  periodSeconds: 10
                  timeoutSeconds: 10
                  failureThreshold: 3
              readiness: *probes
            securityContext:
              allowPrivilegeEscalation: false
              readOnlyRootFilesystem: true
              capabilities: { drop: ["ALL"] }
            resources:
              requests:
                cpu: 100m
                memory: 512Mi
              limits:
                memory: 12Gi
    defaultPodOptions:
      securityContext:
        runAsNonRoot: true
        runAsUser: 1000
        runAsGroup: 1000
        fsGroup: 1000
        fsGroupChangePolicy: OnRootMismatch
    service:
      app:
        ports:
          http:
            port: *port
    ingress:
      app:
        className: internal
        annotations:
          nginx.ingress.kubernetes.io/auth-url: "http://ak-outpost-internal-proxy-outpost.security.svc.cluster.local:9000/outpost.goauthentik.io/auth/nginx"
          nginx.ingress.kubernetes.io/auth-signin: |-
            https://sab.${SECRET_DOMAIN}/outpost.goauthentik.io/start?rd=$escaped_request_uri
          nginx.ingress.kubernetes.io/auth-response-headers: "Set-Cookie,X-authentik-username,X-authentik-groups,X-authentik-email,X-authentik-name,X-authentik-uid"
          nginx.ingress.kubernetes.io/auth-snippet: |
            proxy_set_header X-Forwarded-Host $http_host;
            proxy_set_header X-Original-URL $scheme://$http_host$request_uri;
            proxy_set_header X-Original-Method $request_method;
            proxy_set_header X-Forwarded-Method $request_method;
            proxy_set_header X-Forwarded-For $remote_addr;
        hosts:
          - host: &host "sab.${SECRET_DOMAIN}"
            paths:
              - path: /
                service:
                  identifier: app
                  port: http
        tls:
          - hosts:
              - *host

    persistence:
      config:
        existingClaim: *app
      media:
        type: nfs
        server: nas.${SECRET_DOMAIN}
        path:  /mnt/truenas/cf-nas/data
        globalMounts:
          - path: /data
            readOnly: false
      scripts:
        type: configMap
        name: sabnzbd-scripts
        defaultMode: 0775
        globalMounts:
          - path: /scripts
            readOnly: true
      tmp:
        type: emptyDir
      coredns:
        type: configMap
        name: sabnzbd-coredns
        advancedMounts:
          sabnzbd:
            coredns:
              - path: /etc/coredns/Corefile
                subPath: Corefile
                readOnly: true
      gluetun-auth:
        type: secret
        name: sabnzbd-gluetun-secret
        advancedMounts:
          sabnzbd:
            gluetun:
              - path: /config/auth.toml
                subPath: auth.toml
