---
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: vps-node-exporter
  namespace: observability
spec:
  selector:
    matchLabels:
      app.kubernetes.io/name: vps-exporter
  endpoints:
    - port: metrics
      interval: 30s
      scrapeTimeout: 10s
      path: /metrics
