---
# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/external-secrets.io/externalsecret_v1beta1.json
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: tautulli
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: onepassword
  target:
    name: tautulli-secret
    template:
      engineVersion: v2
      data:
        TAUTULLI__OAUTH_CLIENT_ID: "{{ .TAUTULLI_OAUTH_CLIENT_ID }}"
        TAUTULLI__OAUTH_CLIENT_SECRET: "{{ .TAUTULLI_OAUTH_CLIENT_SECRET }}"
  dataFrom:
    - extract:
        key: tautulli