---
apiVersion: volsync.backube/v1alpha1
kind: ReplicationSource
metadata:
  name: ${APP}
spec:
  sourcePVC: "${VOLSYNC_PVC:=${APP}}"
  trigger:
    schedule: "0 3 * * *"  # Daily at 3 AM
  restic:
    copyMethod: Snapshot
    storageClassName: "${VOLSYNC_STORAGECLASS:=csi-rbd-sc}"
    volumeSnapshotClassName: "${VOLSYNC_STORAGECLASS:=csi-rbd-sc}"
    repository: ${APP}-volsync-secret
    cacheCapacity: "${VOLSYNC_CACHE_CAPACITY:=1Gi}"
    retain:
      daily: 7
      weekly: 4
      monthly: 3
    moverSecurityContext:
      runAsUser: 1000
      runAsGroup: 1000
      fsGroup: 1000