---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: cleanuperr
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: onepassword
  target:
    name: cleanuperr-config
    creationPolicy: Owner
    template:
      engineVersion: v2
      data:
        RADARR__INSTANCES__0__APIKEY: "{{ .RADARR_API_KEY }}"
        SONARR__INSTANCES__0__APIKEY: "{{ .SONARR_API_KEY }}"
        QBITTORRENT__USERNAME: "{{ .QBT_WEBUI_USERNAME }}"
        QBITTORRENT__PASSWORD: "{{ .QBT_WEBUI_PASSWORD }}"
  dataFrom:
    - extract:
        key: sonarr
    - extract:
        key: radarr
    - extract:
        key: qbittorrent
