---
# yaml-language-server: $schema=https://raw.githubusercontent.com/bjw-s-labs/helm-charts/main/charts/other/app-template/schemas/helmrelease-helm-v2.schema.json
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: &app cleanuperr
  namespace: media
spec:
  interval: 1h
  chartRef:
    kind: OCIRepository
    name: app-template
    namespace: flux-system
  driftDetection:
    mode: enabled

  values:
    defaultPodOptions:
      securityContext:
        runAsUser: 1000
        runAsGroup: 568
        fsGroup: 568
        fsGroupChangePolicy: OnRootMismatch
    controllers:
      cleanuperr:
        annotations:
          reloader.stakater.com/auto: "true"
        containers:
          app:
            image:
              repository: ghcr.io/flmorg/cleanuperr
              tag: 1.6.8@sha256:550881bda5dc23755183767e6067434d267c4b87e59aa2698549617c2e4b3f70
            env:
              TZ: ${SECRET_TIMEZONE}
              QUEUECLEANER__ENABLED: true
              SONARR__ENABLED: true
              SONARR__INSTANCES__0__URL: http://sonarr.media.svc.cluster.local:80
              RADARR__ENABLED: true
              RADARR__INSTANCES__0__URL: http://radarr.media.svc.cluster.local:7878
              DOWNLOAD_CLIENT: qBittorrent
              QBITTORRENT__URL: http://qbittorrent-app.media.svc.cluster.local:80
            envFrom:
              - secretRef:
                  name: cleanuperr-config
            resources:
              requests:
                cpu: 10m
                memory: 128Mi
              limits:
                memory: 256Mi
    service:
      app:
        controller: *app
        ports:
          http:
            port: 9705
    ingress:
      app:
        className: internal
        hosts:
          - host: &host "{{ .Release.Name }}.${SECRET_DOMAIN}"
            paths:
              - path: /
                service:
                  identifier: app
                  port: http
        tls:
          - hosts:
              - *host
    persistence:
      config:
        enabled: true
        existingClaim: *app
        advancedMounts:
          cleanuperr:
            app:
              - path: /config