---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: cleanuperr
  namespace: media
spec:
  accessModes: ["ReadWriteOnce"]
  resources:
    requests:
      storage: 10Gi
  storageClassName: csi-rbd-sc
