---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: wizarr
  namespace: media
spec:
  accessModes: ["ReadWriteOnce"]
  resources:
    requests:
      storage: 2Gi
  storageClassName: csi-rbd-sc
