---
# yaml-language-server: $schema=https://raw.githubusercontent.com/bjw-s-labs/helm-charts/main/charts/other/app-template/schemas/helmrelease-helm-v2.schema.json
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: jellyfin
  namespace: media
spec:
  interval: 1h
  chartRef:
    kind: OCIRepository
    name: app-template
    namespace: flux-system
  install:
    remediation:
      retries: -1
    timeout: 10m
  upgrade:
    cleanupOnFail: true
    remediation:
      retries: 3
    timeout: 10m
  values:
    controllers:
      jellyfin:
        annotations:
          reloader.stakater.com/auto: "true"
        containers:
          app:
            image:
              repository: ghcr.io/jellyfin/jellyfin
              tag: sha256:e4d1dc5374344446a3a78e43dd211247f22afba84ea2e5a13cbe1a94e1ff2141
            env:
              TZ: Europe/Oslo
              JELLYFIN_CACHE_DIR: /cache
              JELLYFIN_CONFIG_DIR: /config/config
              JELLYFIN_DATA_DIR: /config
              JELLYFIN_FFMPEG: /usr/lib/jellyfin-ffmpeg/ffmpeg
              JELLYFIN_LOG_DIR: /config/log
              JELLYFIN_WEB_DIR: /usr/share/webapps/jellyfin-web
              DOTNET_SYSTEM_IO_DISABLEFILELOCKING: 'true'
            probes:
              liveness: &probes
                enabled: true
                custom: true
                spec:
                  httpGet:
                    path: /health
                    port: &port 8096
                  initialDelaySeconds: 0
                  periodSeconds: 10
                  timeoutSeconds: 1
                  failureThreshold: 3
              readiness: *probes
              startup:
                enabled: true
                spec:
                  failureThreshold: 30
                  periodSeconds: 10
            securityContext:
              allowPrivilegeEscalation: false
              readOnlyRootFilesystem: true
              capabilities: { drop: ["ALL"] }
            resources:
              requests:
                cpu: 100m
              limits:
                gpu.intel.com/i915: 1
                memory: 8Gi
    defaultPodOptions:
      securityContext:
        runAsNonRoot: true
        runAsUser: 1000
        runAsGroup: 1000
        fsGroup: 1000
        fsGroupChangePolicy: OnRootMismatch
        supplementalGroups: [44]
    service:
      app:
        controller: jellyfin
        ports:
          http:
            port: *port
    ingress:
      app:
        className: internal
        annotations:
          internal-dns.alpha.kubernetes.io/target: "internal.cftollefsen.com"
        hosts:
          - host: "{{ .Release.Name }}.cftollefsen.com"
            paths:
              - path: /
                service:
                  identifier: app
                  port: http
    persistence:
      config:
        existingClaim: jellyfin
        globalMounts:
          - path: /config
      config-cache:
        existingClaim: jellyfin-cache
        globalMounts:
          - path: /config/metadata
      media:
      #   type: persistentVolumeClaim
      #   existingClaim: nas-media-pvc
      #   globalMounts:
      #     - path: /media
        type: nfs
        server: 10.0.30.243
        path: /mnt/truenas/cf-nas/data
        globalMounts:
          - path: /data
            readOnly: true
      tmpfs:
        type: emptyDir
        advancedMounts:
          jellyfin:
            app:
              - path: /cache
                subPath: cache
              - path: /config/log
                subPath: log
              - path: /tmp
                subPath: tmp