---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: pv-jellyfin-cache
  namespace: media
spec:
  accessModes:
    - ReadWriteOnce
  capacity:
    storage: 10Gi
  csi:
    driver: csi.proxmox.sinextra.dev
    fsType: xfs
    volumeAttributes:
      storage: zfs
    volumeHandle: jellyfin-cache/proxmox-ceph/zfs/kube-fs
  storageClassName: proxmox-zfs
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: jellyfin-cache
  namespace: media
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 50Gi
  storageClassName: proxmox-zfs
  volumeName: pv-jellyfin-cache