# File: kubernetes/apps/default/glance/app/externalsvc.yaml
---
apiVersion: v1
kind: Service
metadata:
  name: authentik-outpost
  namespace: default
spec:
  type: ExternalName
  externalName: ak-outpost-authentik-embedded-outpost.security.svc.cluster.local
  ports:
    - port: 9000
      targetPort: 9000
      protocol: TCP

---
# File: kubernetes/apps/default/glance/app/outpost-ingress.yaml
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: glance-outpost
  namespace: default
  annotations:
    external-dns.alpha.kubernetes.io/target: "external.${SECRET_DOMAIN}"
spec:
  ingressClassName: external
  rules:
    - host: glance.${SECRET_DOMAIN}
      http:
        paths:
          - path: /outpost.goauthentik.io
            pathType: Prefix
            backend:
              service:
                name: authentik-outpost
                port:
                  number: 9000
  tls:
    - hosts:
        - glance.${SECRET_DOMAIN}