---
# yaml-language-server: $schema=https://json.schemastore.org/kustomization
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ./externalsecret.yaml
  - ./svc.yaml
  - ./ingress.yaml
  - ./helmrelease.yaml
  - ./gatus.yaml
configMapGenerator:
  - name: glance-configmap
    files:
      - glance.yml=./config/glance.yml
generatorOptions:
  disableNameSuffixHash: true