---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: glance-outpost
  namespace: default
  annotations:
    external-dns.alpha.kubernetes.io/exclude: "true"
spec:
  ingressClassName: external
  rules:
    - host: glance.${SECRET_DOMAIN}
      http:
        paths:
          - path: /outpost.goauthentik.io
            pathType: Prefix
            backend:
              service:
                name: ak-outpost-authentik-embedded-outpost
                namespace: security
                port:
                  number: 9000