---
# yaml-language-server: $schema=https://json.schemastore.org/kustomization
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: flux-system
resources:
  - ./gitrepository-write.yaml
  - ./externalsecret-flux-ssh.yaml
  - ./ai-orchestrator.yaml
  - ./reptile-tracker.yaml
