---
# yaml-language-server: $schema=https://raw.githubusercontent.com/bjw-s-labs/helm-charts/main/charts/other/app-template/schemas/helmrelease-helm-v2.schema.json
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: &app karakeep
spec:
  interval: 30m
  chartRef:
    kind: OCIRepository
    name: app-template
    namespace: flux-system
  values:
    defaultPodOptions:
      securityContext:
        runAsUser: 1000
        runAsGroup: 1000
        runAsNonRoot: true
        fsGroup: 1000
        fsGroupChangePolicy: "OnRootMismatch"

    controllers:
      karakeep:
        forceRename: *app
        annotations:
          reloader.stakater.com/auto: "true"
        containers:
          app:
            image:
              repository: ghcr.io/karakeep-app/karakeep
              tag: 0.29.0
            env:
              BROWSER_WEB_URL: http://karakeep-chrome.default.svc.cluster.local:9222
              CRAWLER_DOWNLOAD_BANNER_IMAGE: true
              CRAWLER_ENABLE_ADBLOCKER: true
              CRAWLER_STORE_SCREENSHOT: true
              DATA_DIR: /data
              DISABLE_SIGNUPS: true
              DISABLE_PASSWORD_AUTH: true
              MEILI_ADDR: http://karakeep-meilisearch.default.svc.cluster.local:7700
              NEXTAUTH_URL: https://karakeep.${SECRET_DOMAIN}
              DISABLE_NEW_RELEASE_CHECK: true
              COREPACK_INTEGRITY_KEYS: 0
              TZ: ${SECRET_TIMEZONE}
            envFrom:
              - secretRef:
                  name: karakeep-secret
            probes:
              liveness:
                enabled: true
              readiness:
                enabled: true
            resources:
              requests:
                cpu: 15m
                memory: 549M
              limits:
                memory: 1Gi

      chrome:
        annotations:
          reloader.stakater.com/auto: "true"
        containers:
          app:
            image:
              repository: gcr.io/zenika-hub/alpine-chrome
              tag: 124
            command:
              - chromium-browser
            args:
              - --headless
              - --no-sandbox
              - --disable-gpu
              - --disable-dev-shm-usage
              - --remote-debugging-address=0.0.0.0
              - --remote-debugging-port=9222
              - --hide-scrollbars
            securityContext:
              capabilities:
                drop:
                  - ALL
            resources:
              requests:
                cpu: 15m
                memory: 256M
              limits:
                memory: 512M

      meilisearch:
        annotations:
          reloader.stakater.com/auto: "true"
        containers:
          app:
            image:
              repository: docker.io/getmeili/meilisearch
              tag: v1.30.0
            args:
              - /bin/meilisearch
              - --experimental-dumpless-upgrade
            env:
              MEILI_NO_ANALYTICS: true
              MEILI_MASTER_KEY:
                valueFrom:
                  secretKeyRef:
                    name: karakeep-secret
                    key: MEILI_MASTER_KEY
            resources:
              requests:
                cpu: 15m
                memory: 105M
              limits:
                memory: 4Gi

    service:
      app:
        forceRename: *app
        primary: true
        controller: *app
        ports:
          http:
            port: &httpPort 3000
      chrome:
        controller: chrome
        ports:
          http:
            port: 9222
      meilisearch:
        controller: meilisearch
        ports:
          http:
            port: 7700

    persistence:
      data:
        existingClaim: *app
        advancedMounts:
          karakeep:
            app:
              - path: /data
      meilisearch-data:
        existingClaim: karakeep-meilisearch
        advancedMounts:
          meilisearch:
            app:
              - path: /meili_data
      cache:
        type: emptyDir
        advancedMounts:
          karakeep:
            app:
              - path: /.cache
      appcache:
        type: emptyDir
        advancedMounts:
          karakeep:
            app:
              - path: /app/apps/web/.next/cache

    ingress:
      app:
        enabled: true
        className: external
        annotations:
          gethomepage.dev/enabled: "true"
          external-dns.alpha.kubernetes.io/target: "external.${SECRET_DOMAIN}"
        hosts:
          - host: &host "karakeep.${SECRET_DOMAIN}"
            paths:
              - path: /
                service:
                  identifier: app
                  port: http
        tls:
          - hosts:
              - *host
