---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: &app kitchenowl
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: onepassword
  target:
    name: *app
    template:
      engineVersion: v2
      data:
        # App
        JWT_SECRET_KEY: "{{ .KITCHENOWL_JWT_TOKEN }}"
        # Database
        DB_TYPE: postgres
        DB_HOST: &dbhost "{{ .POSTGRES_RW_SVC }}"
        DB_PORT: "5432"
        DB_NAME: &dbname kitchenowl
        DB_USER: &dbuser kitchenowl
        DB_PASSWORD: &dbpass "{{ .KITCHENOWL_POSTGRES_PASS }}"
        # Database Init
        INIT_POSTGRES_HOST: *dbhost
        INIT_POSTGRES_DBNAME: *dbname
        INIT_POSTGRES_USER: *dbuser
        INIT_POSTGRES_PASS: *dbpass
        INIT_POSTGRES_SUPER_USER: "{{ .POSTGRES_SUPER_USER }}"
        INIT_POSTGRES_SUPER_PASS: "{{ .POSTGRES_SUPER_PASS }}"
  dataFrom:
    - extract:
        key: kitchenowl
    - extract:
        key: cloudnative-pg