# yaml-language-server: $schema=https://kubernetesjsonschema.dev/v1.18.1-standalone-strict/secret-v1.json
apiVersion: v1
kind: Secret
metadata:
  name: github-webhook-token-secret
stringData:
  token: ENC[AES256_GCM,data:ydKmrrEch9sIAU2m0otld2isZsIWT8EBp+JAZl9YvRU=,iv:6WpJTYJY44MB7ylx9t7nQAbMzXT8OiG8f4YV8lK+n2w=,tag:htFOa49zBCI9vY0vW1FobQ==,type:str]
sops:
  age:
    - recipient: age1am64psa3hmwqnc924p9vuphyp4txekclpsysx6fkqtktgzppgusqfah833
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBaMGdOUzdGemUxOVVhbExC
        RkZEcHVzMWRqdTVNemRtMXBwbTlEdVRyZGhVCnpVMDg2UG1RS0srSTNJY0xFcytr
        NE51c1pQVjZpOXZLV1ZRSy95bzNxVTgKLS0tIGNDR0lDMGRQcHp5OGtaUWcrZ2lV
        WFFwRXRKbGVxUCtHRlYxMVZBNHlXMU0KVegp8MV5hQ95Rhl+VyExRx2XVtF1UEr6
        I0rHewTy/4YJyGThQzPGWFIj17JhsTMHYXcbG57m2QIrjePrlHU7Bw==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2025-05-08T21:53:46Z"
  mac: ENC[AES256_GCM,data:1AEz58A4aXJTeH/JBIfu3fBRe+Rm+ZS1yhrdyTPrvJLX5FtJgLLmpA/oM1s4N7WDbAKRm/pHbTAx1qioRMgwhHKxI5RDQkuZq6SsPc2H8H02rg2Le0o+CxV9GnZb4mIM7LI4uFmaL856VU2cYCY6zmX5TwqX1hJiTLY1R3F4JD8=,iv:kw4qlqTegnutu4NG+kR+BfQAY2p+HOXCGwEa/gLT9Ks=,tag:gDD5/7aDoTndTVau0gj84g==,type:str]
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.10.2
