---
# yaml-language-server: $schema=https://raw.githubusercontent.com/bjw-s-labs/helm-charts/main/charts/other/app-template/schemas/helmrelease-helm-v2.schema.json
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: qbittorrent
  namespace: media
spec:
  interval: 1h
  chartRef:
    kind: OCIRepository
    name: app-template
    namespace: flux-system
  install:
    remediation:
      retries: -1
  upgrade:
    cleanupOnFail: true
    remediation:
      retries: 3
  values:
    controllers:
      qbittorrent:
        containers:
          app:
            image:
              repository: ghcr.io/home-operations/qbittorrent
              tag: 5.1.0@sha256:37aefd713ba31d51255995261616f1144378887bc5f21665a0ebf851fb85f69a
            env:
              TZ: ${SECRET_TIMEZONE}
              QBT_WEBUI_PORT: &port 80
              QBT_TORRENTING_PORT: &torrentPort 50413
            probes:
              liveness: &probes
                enabled: true
                custom: true
                spec:
                  httpGet:
                    path: /api/v2/app/version
                    port: *port
                  initialDelaySeconds: 0
                  periodSeconds: 10
                  timeoutSeconds: 1
                  failureThreshold: 3
              readiness: *probes
              startup:
                enabled: true
                spec:
                  failureThreshold: 30
                  periodSeconds: 10
            securityContext:
              allowPrivilegeEscalation: false
              readOnlyRootFilesystem: true
              capabilities: { drop: ["ALL"] }
            resources:
              requests:
                cpu: 100m
              limits:
                memory: 8Gi
    defaultPodOptions:
      securityContext:
        runAsNonRoot: true
        runAsUser: 1000
        runAsGroup: 1000
        fsGroup: 1000
        fsGroupChangePolicy: OnRootMismatch
    # service:
    #   app:
    #     controller: qbittorrent
    #     type: LoadBalancer
    #     annotations:
    #       lbipam.cilium.io/ips: 10.0.30.95
    #     ports:
    #       http:
    #         primary: true
    #         port: *port
    #       bittorrent:
    #         enabled: true
    #         port: *torrentPort
    #         protocol: TCP
    service:
      app:
        controller: *app
        # nameOverride: *app
        ports:
          http:
            port: *port
      bittorrent:
        controller: *app
        type: LoadBalancer
        annotations:
          metallb.io/loadBalancerIPs: 10.0.30.95 
        ports:
          bittorrent:
            enabled: true
            port: *torrentPort
            protocol: TCP
    ingress:
      app:
        className: internal
        annotations:
          internal-dns.alpha.kubernetes.io/target: "internal.${SECRET_DOMAIN}"
        hosts:
          - host: qbittorrent.${SECRET_DOMAIN}
            paths:
              - path: /
                service:
                  name: app
                  port: *port
    persistence:
      config:
        existingClaim: qbittorrent
      media:
        type: nfs
        server: nas.${SECRET_DOMAIN}
        path: /mnt/truenas/cf-nas/data/media
        globalMounts:
          - path: /media/Downloads/qbittorrent
            subPath: Downloads/qbittorrent
      tmp:
        type: emptyDir
