---
apiVersion: v1
kind: ConfigMap
metadata:
  name: shelfmark-proxy-auth
data:
  security.json: |
    {
      "AUTH_METHOD": "proxy",
      "PROXY_AUTH_USER_HEADER": "X-authentik-username",
      "PROXY_AUTH_LOGOUT_URL": "https://sso.${SECRET_DOMAIN}/outpost.goauthentik.io/sign_out",
      "PROXY_AUTH_ADMIN_GROUP_HEADER": "X-authentik-groups",
      "PROXY_AUTH_ADMIN_GROUP_NAME": "${PROXY_ADMIN_GROUP}"
    }
