---
apiVersion: image.toolkit.fluxcd.io/v1
kind: ImagePolicy
metadata:
  name: reptile-tracker-backend
  namespace: flux-system
spec:
  imageRepositoryRef:
    name: reptile-tracker-backend
  policy:
    numerical:
      order: asc
  filterTags:
    pattern: '^main-([0-9]+)$'
    extract: '$1'
---
apiVersion: image.toolkit.fluxcd.io/v1
kind: ImagePolicy
metadata:
  name: reptile-tracker-frontend
  namespace: flux-system
spec:
  imageRepositoryRef:
    name: reptile-tracker-frontend
  policy:
    numerical:
      order: asc
  filterTags:
    pattern: '^main-([0-9]+)$'
    extract: '$1'
