---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: default
resources:
  - ./helmrelease.yamls
  - ./backendtrafficpolicy.yaml
  - ./externalsecret.yaml
  - ./externalsecret-flux-ssh.yaml
  - ./gitrepository-write.yaml
  - ./imagerepository.yaml
  - ./imagepolicy.yaml
  - ./imageupdateautomation.yaml