---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: sonarr-outpost
  namespace: media
  annotations:
    nginx.ingress.kubernetes.io/backend-protocol: "HTTP"
    nginx.ingress.kubernetes.io/rewrite-target: /$1
spec:
  ingressClassName: internal
  tls:
    - hosts:
        - sonarr.cftollefsen.com
  rules:
    - host: sonarr.cftollefsen.com
      http:
        paths:
          - path: /outpost.goauthentik.io/(.*)
            pathType: ImplementationSpecific
            backend:
              service:
                name: authentik-outpost
                port:
                  number: 9000