---
# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/external-secrets.io/externalsecret_v1.json
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: qbit-manage-private
spec:
  refreshInterval: 5m
  secretStoreRef:
    kind: ClusterSecretStore
    name: onepassword
  target:
    name: qbit-manage-private-secret
    creationPolicy: Owner
    template:
      engineVersion: v2
      data:
        QBIT_USER: "{{ .QBT_WEBUI_USERNAME }}"
        QBIT_PASS: "{{ .QBT_WEBUI_PASSWORD }}"
  dataFrom:
    - extract:
        key: qbittorrent
