---
# yaml-language-server: $schema=https://raw.githubusercontent.com/bjw-s/helm-charts/main/charts/other/app-template/schemas/helmrelease-helm-v2.schema.json
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: &app booklore
spec:
  interval: 1h
  chartRef:
    kind: OCIRepository
    name: app-template
    namespace: flux-system
  maxHistory: 2
  test:
    enable: false
  install:
    remediation:
      retries: 5
  upgrade:
    remediation:
      retries: 5
      strategy: rollback
    cleanupOnFail: true
  rollback:
    timeout: 10m
    recreate: true
    cleanupOnFail: true
  uninstall:
    keepHistory: false
  values:
    controllers:
      *app :
        containers:
          *app :
            image:
              repository: ghcr.io/adityachandelgit/booklore-app
              tag: v0.35.0@sha256:f1a84b4ef2d41c1bcdfae711f9f3de0c99dd5e97b5dc450c37525965224da8ae

            env:
              TZ: "${SECRET_TIMEZONE}"

            probes:
              liveness: &probes
                enabled: true
                custom: true
                spec:
                  httpGet:
                    path: /api/health
                    port: &port 9705
                  initialDelaySeconds: 0
                  periodSeconds: 10
                  timeoutSeconds: 1
                  failureThreshold: 3
              readiness: *probes

            # resources: # Based on goldilocks
            #   requests:
            #     cpu: 15m
            #     memory: 105M
            #   limits:
            #     cpu: 29m
            #     memory: 119M

    service:
      app :
        controller: *app
        ports:
          http:
            port: *port

    ingress:
      app:
        className: internal
        hosts:
          - host: &host "{{ .Release.Name }}.${SECRET_DOMAIN}"
            paths:
              - path: /
                service:
                  identifier: app
                  port: http
        tls:
          - hosts:
              - *host

    persistence:
      config:
        existingClaim: huntarr-config-v1

      books:
        type: nfs
        server: nas.${SECRET_DOMAIN}
        path: /mnt/truenas/cf-nas/data/media
        globalMounts:
          - path: ~/booklore/books
            readOnly: false

      bookdrop:
        type: emptyDir
        globalMounts:
          - path: ~/booklore/bookdrop