---
# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/helm.toolkit.fluxcd.io/helmrelease_v2.json
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: authentik
spec:
  interval: 30m
  chart:
    spec:
      chart: authentik
      version: 2025.6.1
      sourceRef:
        kind: HelmRepository
        name: authentik
        namespace: flux-system
      interval: 5m
  install:
    remediation:
      retries: 3
  upgrade:
    cleanupOnFail: true
    remediation:
      strategy: rollback
      retries: 3
  values:
    global:
      podAnnotations:
        secret.reloader.stakater.com/reload: &secret authentik-secret
      deploymentStrategy:
        type: RollingUpdate
      envFrom:
        - secretRef:
            name: *secret
    authentik:
      redis:
        host: redis-headless.database.svc.cluster.local
        db: 1
    server:
      01-init-db:
        image:
          repository: ghcr.io/home-operations/postgres-init
          tag: 17.5.0@sha256:894a38169bf4135fb1e85a1112c64fc24a267d1191887cbf6fb8c0a17893770d
          pullPolicy: IfNotPresent
        envFrom: &envFrom
          - secretRef:
              name: *secret
      metrics:
        enabled: false
        serviceMonitor:
          enabled: false
      ingress:
        enabled: false
    prometheus:
      rules:
        enabled: false
