---
# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/helm.toolkit.fluxcd.io/helmrelease_v2.json
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: authentik
  namespace: security
spec:
  interval: 30m
  chart:
    spec:
      chart: authentik
      version: 2025.6.1
      sourceRef:
        kind: HelmRepository
        name: authentik
        namespace: flux-system
      interval: 5m
  install:
    remediation:
      retries: 3
  upgrade:
    cleanupOnFail: true
    remediation:
      strategy: rollback
      retries: 3
  values:
    global:
      podAnnotations:
        # secret.reloader.stakater.com/reload: &secret authentik-secret
        reloader.stakater.com/auto: 'true'
      deploymentStrategy:
        type: RollingUpdate
      envFrom:
        - secretRef:
            name: &secret authentik-secret
    authentik:
      redis:
        host: redis.database.svc.cluster.local
        db: 1
        # master:
        #   resources:
        #     limits:
        #       cpu: 2
        #       ephemeral-storage: 2Gi
        #       memory: 2048Mi
        #     requests:
        #       cpu: 100m
        #       ephemeral-storage: 50Mi
        #       memory: 128Mi

      # postgresql:
      #   host: 
      #     fromSecret: authentik-secret
      #     secretKey: AUTHENTIK_POSTGRESQL__HOST
      #   name: 
      #     fromSecret: authentik-secret
      #     secretKey: AUTHENTIK_POSTGRESQL__NAME
      #   # user: 
      #   #   fromSecret: authentik-secret
      #   #   secretKey: AUTHENTIK_POSTGRES_USER
      #   password:
      #     fromSecret: authentik-secret
      #     secretKey: AUTHENTIK_POSTGRES_PASS
    server:
      replicas: 1
      initContainers:
      - name: init-db
        image: ghcr.io/home-operations/postgres-init:17.5
        envFrom:
          - secretRef:
              name: *secret
      metrics:
        enabled: false
        serviceMonitor:
          enabled: false
      ingress:
        enabled: true
        internal:
          ingressClassName: internal
          annotations:
            internal-dns.alpha.kubernetes.io/target: internal.${SECRET_DOMAIN}
            nginx.ingress.kubernetes.io/configuration-snippet: |
              add_header Cache-Control "no-store";
              add_header Pragma "no-cache";
              add_header X-Frame-Options "SAMEORIGIN";
              add_header X-XSS-Protection "1; mode=block";
          hosts:
            - host: &internalHost authentik.${SECRET_DOMAIN}
              paths:
                - path: /
                  pathType: Prefix
                  service:
                    identifier: app
                    port: http
          tls:
            - hosts:
                - *internalHost
    worker:
      replicas: 1
      autoscaling:
        enabled: true
        minReplicas: 1
      resources:
        requests:
          cpu: 200m
        limits:
          memory: 1Gi
    redis:
      global:
        imageRegistry: proxy.registry.beryju.io
        security:
          allowInsecureImages: true
      enabled: true
      networkPolicy:
        extraIngress:
          - ports:
              - port: 15020
                protocol: TCP
    prometheus:
      rules:
        enabled: false
