---
# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/helm.toolkit.fluxcd.io/helmrelease_v2.json
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: authentik
  namespace: security
spec:
  interval: 30m
  chart:
    spec:
      chart: authentik
      version: 2025.6.1
      sourceRef:
        kind: HelmRepository
        name: authentik
        namespace: flux-system
      interval: 5m
  install:
    remediation:
      retries: -1
  upgrade:
    cleanupOnFail: true
    remediation:
      strategy: rollback
      retries: -1
  values:
    global:
      podAnnotations:
        # secret.reloader.stakater.com/reload: &secret authentik-secret
        reloader.stakater.com/auto: 'true'
      deploymentStrategy:
        type: RollingUpdate
      envFrom:
        - secretRef:
            name: &secret authentik-secret
    redis:
      enabled: false
    authentik:
      redis:
          host: dragonfly.database.svc.cluster.local
    server:
      replicas: 1
      initContainers:
      - name: init-db
        image: ghcr.io/home-operations/postgres-init:17.5
        envFrom:
          - secretRef:
              name: *secret
      metrics:
        enabled: false
        serviceMonitor:
          enabled: false
      ingress:
        enabled: true
        ingressClassName: internal
        annotations:
          internal-dns.alpha.kubernetes.io/target: internal.${SECRET_DOMAIN}
          nginx.ingress.kubernetes.io/configuration-snippet: |
            add_header Cache-Control "no-store";
            add_header Pragma "no-cache";
            add_header X-Frame-Options "SAMEORIGIN";
            add_header X-XSS-Protection "1; mode=block";
        hosts:
          - host: &internalHost authentik.${SECRET_DOMAIN}
            paths:
              - path: /
                pathType: Prefix
                service:
                  identifier: app
                  port: http
        tls:
          - hosts:
              - *internalHost
      probes:
        readiness:
          enabled: true
          spec:
            initialDelaySeconds: 30 
            periodSeconds: 10
            timeoutSeconds: 5
            failureThreshold: 3
    worker:
      replicas: 1
      autoscaling:
        enabled: true
        minReplicas: 1
      resources:
        requests:
          cpu: 200m
        limits:
          memory: 1Gi
    prometheus:
      rules:
        enabled: false
