---
# yaml-language-server: $schema=https://json.schemastore.org/kustomization
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ./ingress.yaml  # Keep using nginx-ingress for VPS routing
  # - ./httproute.yaml  # Gateway API doesn't support VPS routing
  - ./externalsecret.yaml
  - ./helmrelease.yaml
  - ./configmap.yaml
  - ./internal-certificate.yaml
  - ./base-blueprints.yaml
  - ./referencegrant.yaml
