---
# yaml-language-server: $schema=https://raw.githubusercontent.com/bjw-s-labs/helm-charts/main/charts/other/app-template/schemas/helmrelease-helm-v2.schema.json
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: &app cleanuparr
  namespace: media
spec:
  interval: 1h
  chartRef:
    kind: OCIRepository
    name: app-template
    namespace: flux-system
  driftDetection:
    mode: enabled
  install:
    remediation:
      retries: -1
  upgrade:
    cleanupOnFail: true
    remediation:
      retries: 3
  values:
    controllers:
      cleanuparr:
        annotations:
          reloader.stakater.com/auto: "true"
        containers:
          app:
            image:
              repository: ghcr.io/cleanuparr/cleanuparr
              tag: 2.4.0@sha256:ff7e582623dae324a9710f340bb09e7de6d5fd249aeb73f39cf240c0f9de8890
            args: ["/app/Cleanuparr"]
            env:
              TZ: ${SECRET_TIMEZONE}
              PORT: &port 9705
              # BASE_PATH: '/'
              # QUEUECLEANER__ENABLED: true
              # SONARR__ENABLED: true
              # SONARR__INSTANCES__0__URL: http://sonarr.media.svc.cluster.local:80
              # RADARR__ENABLED: true
              # RADARR__INSTANCES__0__URL: http://radarr.media.svc.cluster.local:7878
              # DOWNLOAD_CLIENT: qBittorrent
              # QBITTORRENT__URL: http://qbittorrent-app.media.svc.cluster.local:80
              # DOWNLOADCLEANER__ENABLED: true
            envFrom:
              - secretRef:
                  name: cleanuparr-config
            resources: # Based on goldilocks
              requests:
                cpu: 15m
                memory: 352M
              limits:
                memory: 446M
    defaultPodOptions:
      securityContext:
        fsGroup: &pgid 1000
        fsGroupChangePolicy: OnRootMismatch
        
    service:
      app:
        controller: *app
        ports:
          http:
            port: *port
    ingress:
      app:
        className: internal
        hosts:
          - host: &host "{{ .Release.Name }}.${SECRET_DOMAIN}"
            paths:
              - path: /
                service:
                  identifier: app
                  port: http
        tls:
          - hosts:
              - *host
    persistence:
      config:
        enabled: true
        existingClaim: *app
        advancedMounts:
          cleanuparr:
            app:
              - path: /config
      tmp:
        type: emptyDir
        advancedMounts:
          cleanuparr:
            app:
              - path: /tmp
                subPath: tmp