---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: smtp-relay
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: onepassword
  target:
    name: smtp-relay-secret
    template:
      data:
        SENDGRID_API_KEY: "{{ .SENDGRID_SMTP_API_KEY }}"
  dataFrom:
    - extract:
        key: sendgrid