apiVersion: v1
kind: Secret
metadata:
  name: onepassword-token
  namespace: external-secrets
type: Opaque
stringData:
  token: ENC[AES256_GCM,data:oysFnHyq763fpdweB5Q88OY/c1tKBiZ/+lxtXgs6GPV5vnJhM+nsbqt4L9MkAH4TSKYQoxZP8tan5UJLrTWLnpoXcmtbkLMAjHWF8Hq0P9J1iBejnxCLHujxMWfIUTfUqLd9lLmqBHOWFcH9WEZReI16Xpi92Q+HGDZMXAvRrzxqeoiWMzDE/v+VSNZw1D0dYoWiRa9XfG+emOdU1d1Ug6ljPb1xW6vmptFY8g7jl0KQ2ktZtRv0TAW96oJkyuVMON5xAgu8sEsI0r2RA10d++96OsE6Nb3BVvthEJ8XK2y5XAJZ/m1N/VSmgS+h0euMOdsYxIgOjlq1FU6uLPasrlMXMXbuCVdNzlGLv84QziiQgIuKRFu+TDzjvFZMcPYmYnZ/+RXLKxZwhTXH4joTBX56Yu1Rpg2BpT4CAAM6msb5XhdfvrfNhhDMmOgVUi1eXn/tY1sgPQkhCbsqQbHLuXrPSfNiR1tMC5aTgYFwQHKbU6gF0uTPgzw39B7wLp3TFNwzPOG8HvU6GlfiTqhMULcoIbu8n2IC+eP8b/AHAgB8S6aFk+tDltOIVCNamgHD2kkcn4auuGIZbeLpQUWJtnXe+MiF5ZsUqocYKIKXT/5e3LgWwy/SJbndthl+s5OgPwF0OKi52Vu4eSbwrdeJkWJuyzZS48oirn82zIZ7+STpTlAkCuVZ4yQ0b/pP7DkO3WmNzSNfAyBNzBcw9Rqky86Xxesh2Z3tB6A0xQb9wuw4rgPpZXSxN8kuWcB10tcgXTHTsuugYP4HDQopTxsQdR3B++PSBohIP5DS8GlYCNjgeal9E6VveDYsZ5oA1M9R4yajaN9RAg4e8X1Ey4sV/nt1,iv:/NoomYRn05fCwNEeBzB/ut3UbbZltX22d/s8f32Dwp4=,tag:P5N4HQIc/4E3Itqf3zLbMQ==,type:str]
sops:
  age:
    - recipient: age1am64psa3hmwqnc924p9vuphyp4txekclpsysx6fkqtktgzppgusqfah833
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBFS1dmV2NnbHdOWUVwZEVn
        N1Rob055UUlGeWJ0Ylp4NnBkdHhIQXpmaEJjCkxOWWlxcVoxM29pYVphYnlaTzBk
        R2s3Y3dLSDQ5WFJlRnlHMllxUXpUdDgKLS0tIEdaOUw4bi9mOXE0N0ZBTzI3NGVp
        ZDBkK1JpTmJnRzFEZ0FwOFRMendQVGsKsrgosp6WNT+IwElOjz5PoJaGGPRShxL+
        YI/tBC3qPv238NFBqjNPMBoEOBVzOFOGizta9cCO9vlBbyhTVqfRaQ==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2025-05-11T21:49:36Z"
  mac: ENC[AES256_GCM,data:9Jfxq6nx7oVqy4UGkCskGi0MhHCl9qedUDfKtK67ajz4qWGbpYnQwOynsXClaSInsh13J6tYI2PiYIyhnx10ZklB2QZDIa9D0JgxIfeO8kWOGcLZ/4xHWsSODercF4CBap/EnFZrvElG5oAZy/Gh2RtWgaBzHqLIHxZ2s3lAoe0=,iv:CfUq98Kj/nomkPlAQhtg2nOP/eMhrVq9deO2V7r+UzI=,tag:nRA6BbMtQN9AQ9oG1v9w4g==,type:str]
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.10.2
