---
# yaml-language-server: $schema=https://raw.githubusercontent.com/yannh/kubernetes-json-schema/refs/heads/master/v1.32.2/configmap-v1.json
apiVersion: v1
kind: ConfigMap
metadata:
  name: gatus-public-configmap
  namespace: observability
data:
  config.yaml: |
    web:
      port: 80
    storage:
      type: sqlite
      path: /config/sqlite.db
      caching: true
    metrics: true
    debug: false
    ui:
      title: Public Status | Gatus
      header: Public Status
    connectivity:
      checker:
        target: 1.1.1.1:53
        interval: 1m
    endpoints: []
    alerting:
      custom:
        url: https://n8n-webhook.cftollefsen.com/webhook/gatus
        method: POST
        headers:
          Content-Type: application/json
        body: |
          {
            "endpoint_name": "[ENDPOINT_NAME]",
            "group": "[ENDPOINT_GROUP]",
            "alert_state": "[ALERT_TRIGGERED_OR_RESOLVED]",
            "description": "[ALERT_DESCRIPTION]"
          }
        default-alert:
          description: health-check failed
          send-on-resolved: true
          failure-threshold: 3
          success-threshold: 3