---
# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/external-secrets.io/externalsecret_v1.json
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: homarr
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: onepassword
  target:
    name: homarr-secret
    template:
      engineVersion: v2
      data:
        # Homarr
        SECRET_ENCRYPTION_KEY: "{{ .HOMARR_SECRET_ENCRYPTION_KEY }}"
        # Authentik OIDC
        AUTH_OIDC_CLIENT_ID: "{{ .HOMARR_AUTHENTIK_CLIENT_ID }}"
        AUTH_OIDC_CLIENT_SECRET: "{{ .HOMARR_AUTHENTIK_CLIENT_SECRET }}"
        # Database
        DATABASE_HOST: &dbHost "{{ .POSTGRES_RW_SVC }}"
        DATABASE_PORT: &dbPort "5432"
        DATABASE_NAME: &dbName homarr
        DATABASE_USER: &dbUser "{{ .HOMARR_POSTGRES_USER }}"
        DATABASE_PASSWORD: &dbPass "{{ .HOMARR_POSTGRES_PASS }}"
        DATABASE_URL: "postgresql://{{ .HOMARR_POSTGRES_USER }}:{{ .HOMARR_POSTGRES_PASS }}@{{ .POSTGRES_RW_SVC }}:5432/homarr?sslmode=require"
        # Postgres Init
        INIT_POSTGRES_DBNAME: *dbName
        INIT_POSTGRES_HOST: *dbHost
        INIT_POSTGRES_PORT: *dbPort
        INIT_POSTGRES_USER: *dbUser
        INIT_POSTGRES_PASS: *dbPass
        INIT_POSTGRES_SUPER_PASS: "{{ .POSTGRES_SUPER_PASS }}"
        # Redis
        REDIS_HOST: "dragonfly.database.svc.cluster.local"
        REDIS_PORT: "6379"
        REDIS_DATABASE_INDEX: "2"
  dataFrom:
    - extract:
        key: cloudnative-pg
    - extract:
        key: homarr