---
# yaml-language-server: $schema=https://crd.movishell.pl/external-secrets.io/externalsecret_v1.json
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: outline
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: onepassword
  target:
    name: outline-secret
    template:
      engineVersion: v2
      data:
        BETTER_AUTH_SECRET: "{{ .OUTLINE_SECRET_KEY }}"
        DATABASE_URL: "postgres://{{ .KAN_POSTGRES_USER }}:{{ .KAN_POSTGRES_PASS }}@{{ .POSTGRES_RW_SVC }}:5432/kan?sslmode=disable"
        NEXT_PUBLIC_ALLOW_CREDENTIALS: "true"

  dataFrom:
    - extract:
        key: cloudnative-pg
    - extract:
        key: kan
