---
# yaml-language-server: $schema=https://raw.githubusercontent.com/bjw-s-labs/helm-charts/main/charts/other/app-template/schemas/helmrelease-helm-v2.schema.json
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: &app kan
spec:
  interval: 1h
  chartRef:
    kind: OCIRepository
    name: app-template
    namespace: flux-system
  install:
    remediation:
      retries: 3
  upgrade:
    cleanupOnFail: true
    remediation:
      retries: 3
  values:
    controllers:
      kan:
        strategy: Recreate

        annotations:
          reloader.stakater.com/auto: "true"

        initContainers:
          init-db:
            image:
              repository: ghcr.io/home-operations/postgres-init
              tag: 18.4.0@sha256:ebd9d30add17acdf935d73eb004758c7dfd9388aaa605fda70ad74378ab92aec
            envFrom: &envFrom
              - secretRef:
                  name: kan-secret

        containers:
          app:
            image:
              repository: ghcr.io/kanbn/kan
              tag: 0.5.6@sha256:3509af72635922b8195fc08e052f6257f8a05c50c8afcadc636f78c717667673
              pullPolicy: IfNotPresent
            env:
                NEXT_PUBLIC_BASE_URL: https://kan.${SECRET_DOMAIN}
                TZ: ${SECRET_TIMEZONE}
                PORT: &port 3000

            envFrom: *envFrom
            resources:
              requests:
                cpu: 15m
                memory: 386Mi
              limits:
                memory: 512Mi

    service:
      app:
        controller: *app
        ports:
          http:
            port: *port
    route:
      external:
        annotations:
          external-dns.alpha.kubernetes.io/target: external.${SECRET_DOMAIN}
        hostnames: ["{{ .Release.Name }}.${SECRET_DOMAIN}"]
        parentRefs:
          - name: external
            namespace: network
            sectionName: https
        rules:
          - backendRefs:
              - identifier: app
                port: *port
      internal:
        hostnames: ["kanban.${SECRET_DOMAIN}"]
        parentRefs:
          - name: internal
            namespace: network
            sectionName: https
        rules:
          - backendRefs:
              - identifier: app
                port: *port

    persistence:
          tmpfs:
            type: emptyDir
