---
# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/kustomize.toolkit.fluxcd.io/kustomization_v1.json
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: &app shelfmark
  namespace: &namespace media
spec:
  commonMetadata:
    labels:
      app.kubernetes.io/name: shelfmark
  components:
    - ../../../../components/ceph-rbd
    - ../../../../components/gatus/guarded
    - ../../../../components/proxy-application
    # - ../../../../components/ext-auth  # Temporarily disabled to fix proxy auth config
  interval: 1h
  path: "./kubernetes/apps/media/shelfmark/app"
  postBuild:
    substitute:
      APP: *app
      EXT_AUTH_PORT: "8084"
      GROUP: Media
      SUBDOMAIN: *app
      DESCRIPTION: Book and audiobook downloader
      CEPH_RBD_CAPACITY: 5Gi
      PROXY_ADMIN_PARENT: media-admins
    substituteFrom:
      - name: cluster-secrets
        kind: Secret
  prune: true
  sourceRef:
    kind: GitRepository
    name: flux-system
    namespace: flux-system
  targetNamespace: *namespace
  timeout: 5m
  wait: false