---
# yaml-language-server: $schema=https://json.schemastore.org/kustomization
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ./externalsecret.yaml
  - ./configmap.yaml
  - ./helmrelease.yaml
  # Simplified job that just outputs credentials
  - ./outline-bucket-job.yaml
  # RBAC not needed since we're not creating K8s secrets
  # - ./outline-bucket-rbac.yaml