---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: radarr
  namespace: media
spec:
  accessModes: ["ReadWriteMany"]
  resources:
    requests:
      storage: 5Gi
  storageClassName: csi-rbd-sc
