---
# yaml-language-server: $schema=https://cluster-schemas.pages.dev/helm.toolkit.fluxcd.io/helmrelease_v2.json
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: &app mariadb
spec:
  interval: 30m
  chartRef:
    kind: OCIRepository
    name: mariadb
    namespace: flux-system
  install:
    remediation:
      retries: 3
  upgrade:
    cleanupOnFail: true
    remediation:
      strategy: rollback
      retries: 3
  values:
    auth:
      usePasswordFiles: false
      existingSecret: mariadb-secret
    metrics:
      enabled: true
      resourcesPreset: small
      serviceMonitor:
        enabled: true
    primary:
      resourcesPreset: small
      persistence:
        enabled: true
        existingClaim: *app
      initdbScripts:
        init-booklore.sql: |
          CREATE DATABASE IF NOT EXISTS booklore;
          CREATE USER IF NOT EXISTS '${booklore-db-username}'@'%' IDENTIFIED BY '${booklore-db-password}';
          GRANT ALL PRIVILEGES ON booklore.* TO '${booklore-db-username}'@'%';
          FLUSH PRIVILEGES;
