---
# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/kustomize.toolkit.fluxcd.io/kustomization_v1.json
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: &app mariadb-operator
  namespace: database
spec:
  targetNamespace: database
  commonMetadata:
    labels:
      app.kubernetes.io/name: *app
  path: ./kubernetes/apps/database/mariadb-operator/app
  prune: true
  sourceRef:
    kind: GitRepository
    name: flux-system
    namespace: flux-system
  wait: true
  interval: 30m
  retryInterval: 1m
  timeout: 5m
---
# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/kustomize.toolkit.fluxcd.io/kustomization_v1.json
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: mariadb-operator-instance
  namespace: database
spec:
  targetNamespace: database
  commonMetadata:
    labels:
      app.kubernetes.io/name: mariadb-operator-instance
  dependsOn:
    - name: mariadb-operator
    - name: external-secrets
      namespace: external-secrets
    - name: ceph-csi-rbd
      namespace: ceph-csi-rbd
  path: ./kubernetes/apps/database/mariadb-operator/instance
  prune: true
  sourceRef:
    kind: GitRepository
    name: flux-system
    namespace: flux-system
  wait: true
  interval: 30m
  retryInterval: 1m
  timeout: 10m
  postBuild:
    substituteFrom:
      - name: cluster-secrets
        kind: Secret
