---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: bazarr
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: onepassword
  target:
    name: bazarr-secret
    creationPolicy: Owner
    template:
      engineVersion: v2
      data:
        #Restic backup
        RESTIC_REPOSITORY: "/repository/bazarr"
        RESTIC_PASSWORD: "{{ .RESTIC_PASSWORD }}"
  dataFrom:
    - extract:
        key: restic