---
# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/external-secrets.io/externalsecret_v1.json
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: bazarr
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: onepassword
  target:
    name: bazarr-secret
    creationPolicy: Owner
    template:
      engineVersion: v2
      data:
        # Bazarr PostgreSQL configuration
        POSTGRES_ENABLED: "true"
        POSTGRES_HOST: &dbHost "{{ .POSTGRES_RW_SVC }}"
        POSTGRES_PORT: "5432"
        POSTGRES_DATABASE: "bazarr"
        POSTGRES_USERNAME: &dbUser "{{ .BAZARR_POSTGRES_USER }}"
        POSTGRES_PASSWORD: &dbPass "{{ .BAZARR_POSTGRES_PASS }}"

        # Init container configuration
        INIT_POSTGRES_DBNAME: bazarr
        INIT_POSTGRES_HOST: *dbHost
        INIT_POSTGRES_USER: *dbUser
        INIT_POSTGRES_PASS: *dbPass
        INIT_POSTGRES_SUPER_PASS: "{{ .POSTGRES_SUPER_PASS }}"

        # Restic backup
        RESTIC_REPOSITORY: "/repository/bazarr"
        RESTIC_PASSWORD: "{{ .RESTIC_PASSWORD }}"
  dataFrom:
    - extract:
        key: cloudnative-pg
    - extract:
        key: bazarr
    - extract:
        key: restic
