---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: bazarr
  namespace: media
spec:
  accessModes: ["ReadWriteOnce"]
  volumeMode: Filesystem
  resources:
    requests:
      storage: 5Gi
  storageClassName: csi-rbd-sc
