apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: ceph-csi-rbd
  namespace: ceph-csi-rbd
spec:
  interval: 5m
  chart:
    spec:
      # renovate: registryUrl=https://ceph.github.io/csi-charts
      chart: ceph-csi-rbd
      version: 3.14.0
      sourceRef:
        kind: HelmRepository
        name: ceph-csi
        namespace: flux-system
      interval: 5m
  install:
    remediation:
      retries: -1
    timeout: 10m
  upgrade:
    cleanupOnFail: true
    remediation:
      retries: 3
    timeout: 10m
  #See https://github.com/ceph/ceph-csi/blob/devel/charts/ceph-csi-cephfs/values.yaml
  values:
    csiConfig:
    - clusterID: "e4a4c987-4801-40ad-a6ae-bfdecbec3df4" #FSID of ceph cluster
      monitors:
      - 10.0.30.10:6789
      - 10.0.30.11:6789
      - 10.0.30.12:6789
