apiVersion: v1
kind: Secret
metadata:
    name: cluster-secrets
stringData:
    SECRET_DOMAIN: ENC[AES256_GCM,data:KmMlll0M33AbMqRWvR0A,iv:mpA6fKo/EQjCQZBEXTtg4hvr2ogekQrByvRxlyM1mns=,tag:yP0A8t+bTxvJPU1chEHklg==,type:str]
    SECRET_TIMEZONE: ENC[AES256_GCM,data:KmWGDiNaNixaOOI=,iv:Cryj/ZshYhIbtFrk8UpF24cyGe9Ukz4I0hfSRFM/5TQ=,tag:rvIchsUItk1Crx1uyVE1NQ==,type:str]
    SECRET_DOMAIN_NAME: ENC[AES256_GCM,data:ygbUvmbqLLVBTTo=,iv:+1LQwgQdCOaq0q/Y20ZUkFv8IMXcyTVHA+IA7V8xcWo=,tag:dgTfQKEM5srs/b8ygwF4dA==,type:str]
    VPS_PUBLIC_IP: ENC[AES256_GCM,data:yI8xG7S89yoazVIg42A=,iv:oHr9WFh5NCAf0JaCeWdVOLSbJHUjgDxvAOyK86nuDwM=,tag:+jBuIWcd2URRioKDWRiCGw==,type:str]
    DESKTOP_LAN_IP: ENC[AES256_GCM,data:Hln0arkKWkDURxs=,iv:VseK87nQ8iDFSGN58StCASmCMDfPMyZ9v7dmefrXhbk=,tag:9Zsugy/8aWPG+if583knGQ==,type:str]
    FORGE_GIT_HOST: ENC[AES256_GCM,data:tuP2YPF7xIRg5A==,iv:NCCfJs3Kku7pTQX9QImJD072uqrvCTFEZFR6VbSaJK8=,tag:YNNDVODuIt9XEII1PhNyEQ==,type:str]
    FORGE_API_HOST: ENC[AES256_GCM,data:zAnVQT4QgaiJUU2i2O8=,iv:0ScZqFdmTvM7Y+Rl2ONza3WclS0HGGTwZcmQ/UHkBoI=,tag:WadGnt/CyZA2sXA4iRQDxw==,type:str]
    FORGE_MACHINE_USER: ENC[AES256_GCM,data:t2X6+eNa6YGKLAbJvBAdkTjMiGOCEw==,iv:99SHLPHfsQlVbx6KqLYYv3yf6cgit6mVWqIFbUG0brE=,tag:Lu7wpIjT62/M9iAnU5KR7Q==,type:str]
    FORGE_COMMIT_EMAIL: ENC[AES256_GCM,data:yvfyjckNJGJqYFxGrjwPM2uBQcK+nFafSn/xLP9IhRwlVBfn2nM/aiAtTinn864XLb/RMz5I0qAn,iv:LOFe8TJ0zqBcl5iX1SajgsG+CL/eJ25i3S0+fhh0hKA=,tag:H3f7NgqopMDY14FKjfKuog==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBJQmg3QlZrMWZzV3ArMjN4
            b0UwNDYwNENQRnlvMDkrN2IzSDFWVU9iZ1U4ClhJNlRLTmlPWXgxT1dlREU5NGp0
            VGd1Zm9DZitNaWhWSDlyalZ0Vk96NnMKLS0tIEZFbGhRMlpsbjUxOGJoeEJsaVJz
            Zk9IeXpZNGV1N08vTTBWRkR3WUxuTmMKmekALT1HvRbO5TZ2AEN9jTBIv4WpvLqo
            nZHb8vdqG9NXJkB1PuGblXXDOOFqUnKWeoCnIA+jUFLsJhkk/v7rwA==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1am64psa3hmwqnc924p9vuphyp4txekclpsysx6fkqtktgzppgusqfah833
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-09-14T23:23:25Z"
    mac: ENC[AES256_GCM,data:13UxM4vEAWDltboi5B7auIsnKqDPlFL8Mr3WLvE+jaCYk1Ud9KT2Vn4xnhi8oTksa2D7qB3ALVy1bXAimrCUSkYezpx/HsvcGl6pLvB4c+NzUmUMqgNsKGsD8ZECH9BKcDnZ5R+Qbt0rFFVDQweaQXm3LQSTwNSfw4zShlDXSFA=,iv:D8lnlbwuGuS35Kd3LYLmi8a2ht/rZcW7FCH+BC6nl4Q=,tag:5yDOReWdIRfZNteL/9ZqrQ==,type:str]
    mac_only_encrypted: true
    version: 3.13.3
