apiVersion: v1
kind: Secret
metadata:
    name: cluster-secrets
stringData:
    SECRET_DOMAIN: ENC[AES256_GCM,data:KmMlll0M33AbMqRWvR0A,iv:mpA6fKo/EQjCQZBEXTtg4hvr2ogekQrByvRxlyM1mns=,tag:yP0A8t+bTxvJPU1chEHklg==,type:str]
    SECRET_TIMEZONE: ENC[AES256_GCM,data:KmWGDiNaNixaOOI=,iv:Cryj/ZshYhIbtFrk8UpF24cyGe9Ukz4I0hfSRFM/5TQ=,tag:rvIchsUItk1Crx1uyVE1NQ==,type:str]
    SECRET_DOMAIN_NAME: ENC[AES256_GCM,data:ygbUvmbqLLVBTTo=,iv:+1LQwgQdCOaq0q/Y20ZUkFv8IMXcyTVHA+IA7V8xcWo=,tag:dgTfQKEM5srs/b8ygwF4dA==,type:str]
    VPS_PUBLIC_IP: ENC[AES256_GCM,data:yI8xG7S89yoazVIg42A=,iv:oHr9WFh5NCAf0JaCeWdVOLSbJHUjgDxvAOyK86nuDwM=,tag:+jBuIWcd2URRioKDWRiCGw==,type:str]
sops:
    age:
        - recipient: age1am64psa3hmwqnc924p9vuphyp4txekclpsysx6fkqtktgzppgusqfah833
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBJQmg3QlZrMWZzV3ArMjN4
            b0UwNDYwNENQRnlvMDkrN2IzSDFWVU9iZ1U4ClhJNlRLTmlPWXgxT1dlREU5NGp0
            VGd1Zm9DZitNaWhWSDlyalZ0Vk96NnMKLS0tIEZFbGhRMlpsbjUxOGJoeEJsaVJz
            Zk9IeXpZNGV1N08vTTBWRkR3WUxuTmMKmekALT1HvRbO5TZ2AEN9jTBIv4WpvLqo
            nZHb8vdqG9NXJkB1PuGblXXDOOFqUnKWeoCnIA+jUFLsJhkk/v7rwA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-10-25T23:25:22Z"
    mac: ENC[AES256_GCM,data:P+WPs81eGrwxyFgTba+7VWicV39OpxiJzCuSmVgDMbfpcUocB4Er6ADNyXGVIvcMEAUYUh/QuDFz+uBa2F2FrDyVRk6ONZt4r6GzoWDYl/XgHa0Gt7VUyqXuPU9OId/+rVGRh0padd4IVhHxLMfynZLsCmb3yLuhj9Y/KiJ5oWQ=,iv:6V154RFgpk7oyrtn0XRzACIaDyWOQL9c7ooV4wmo57g=,tag:B4LnlOZKiUlKgqxe0HZd7g==,type:str]
    encrypted_regex: ^(data|stringData)$
    mac_only_encrypted: true
    version: 3.10.2
