apiVersion: v1
kind: Secret
metadata:
  name: cluster-secrets
stringData:
  SECRET_DOMAIN: ENC[AES256_GCM,data:KmMlll0M33AbMqRWvR0A,iv:mpA6fKo/EQjCQZBEXTtg4hvr2ogekQrByvRxlyM1mns=,tag:yP0A8t+bTxvJPU1chEHklg==,type:str]
  SECRET_TIMEZONE: ENC[AES256_GCM,data:KmWGDiNaNixaOOI=,iv:Cryj/ZshYhIbtFrk8UpF24cyGe9Ukz4I0hfSRFM/5TQ=,tag:rvIchsUItk1Crx1uyVE1NQ==,type:str]
  SECRET_DOMAIN_NAME: ENC[AES256_GCM,data:ygbUvmbqLLVBTTo=,iv:+1LQwgQdCOaq0q/Y20ZUkFv8IMXcyTVHA+IA7V8xcWo=,tag:dgTfQKEM5srs/b8ygwF4dA==,type:str]
sops:
  age:
    - recipient: age1am64psa3hmwqnc924p9vuphyp4txekclpsysx6fkqtktgzppgusqfah833
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBJQmg3QlZrMWZzV3ArMjN4
        b0UwNDYwNENQRnlvMDkrN2IzSDFWVU9iZ1U4ClhJNlRLTmlPWXgxT1dlREU5NGp0
        VGd1Zm9DZitNaWhWSDlyalZ0Vk96NnMKLS0tIEZFbGhRMlpsbjUxOGJoeEJsaVJz
        Zk9IeXpZNGV1N08vTTBWRkR3WUxuTmMKmekALT1HvRbO5TZ2AEN9jTBIv4WpvLqo
        nZHb8vdqG9NXJkB1PuGblXXDOOFqUnKWeoCnIA+jUFLsJhkk/v7rwA==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2025-06-05T22:25:17Z"
  mac: ENC[AES256_GCM,data:DmEtgSkeGE1zLHoa1l2TkXrH/3fw6O7giGBGTbD0VodeEH7nn/RRYnZZh4giTH9wEpsfc5IAtC4Gr+z6lVyneWGuxEyj9VXlIAe0FTrZx+/VcNu30HFCES9kUdQqpg0lQ7vKq38hZ0SRtGMtJVwqRjMq1O7Zoi/uPOppT16pumg=,iv:8eSGu9pWUGzlcs89KwJPEB9peunccz3gIGvlIyN6NPE=,tag:6a/RcCA2MgSM0ay78ukxww==,type:str]
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.10.2
