apiVersion: v1
kind: Secret
metadata:
    name: cluster-secrets
stringData:
    SECRET_DOMAIN: ENC[AES256_GCM,data:KmMlll0M33AbMqRWvR0A,iv:mpA6fKo/EQjCQZBEXTtg4hvr2ogekQrByvRxlyM1mns=,tag:yP0A8t+bTxvJPU1chEHklg==,type:str]
    SECRET_TIMEZONE: ENC[AES256_GCM,data:KmWGDiNaNixaOOI=,iv:Cryj/ZshYhIbtFrk8UpF24cyGe9Ukz4I0hfSRFM/5TQ=,tag:rvIchsUItk1Crx1uyVE1NQ==,type:str]
    SECRET_DOMAIN_NAME: ENC[AES256_GCM,data:ygbUvmbqLLVBTTo=,iv:+1LQwgQdCOaq0q/Y20ZUkFv8IMXcyTVHA+IA7V8xcWo=,tag:dgTfQKEM5srs/b8ygwF4dA==,type:str]
    VPS_PUBLIC_IP: ENC[AES256_GCM,data:yI8xG7S89yoazVIg42A=,iv:oHr9WFh5NCAf0JaCeWdVOLSbJHUjgDxvAOyK86nuDwM=,tag:+jBuIWcd2URRioKDWRiCGw==,type:str]
    DESKTOP_LAN_IP: ENC[AES256_GCM,data:Hln0arkKWkDURxs=,iv:VseK87nQ8iDFSGN58StCASmCMDfPMyZ9v7dmefrXhbk=,tag:9Zsugy/8aWPG+if583knGQ==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBJQmg3QlZrMWZzV3ArMjN4
            b0UwNDYwNENQRnlvMDkrN2IzSDFWVU9iZ1U4ClhJNlRLTmlPWXgxT1dlREU5NGp0
            VGd1Zm9DZitNaWhWSDlyalZ0Vk96NnMKLS0tIEZFbGhRMlpsbjUxOGJoeEJsaVJz
            Zk9IeXpZNGV1N08vTTBWRkR3WUxuTmMKmekALT1HvRbO5TZ2AEN9jTBIv4WpvLqo
            nZHb8vdqG9NXJkB1PuGblXXDOOFqUnKWeoCnIA+jUFLsJhkk/v7rwA==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1am64psa3hmwqnc924p9vuphyp4txekclpsysx6fkqtktgzppgusqfah833
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-09-12T17:10:48Z"
    mac: ENC[AES256_GCM,data:/gQGARI7180gbCPfvfBrtayvXeRT+EEFyBuDBueZVdm9s0mq/XLALYwB50bQ5hy1X93fx0rLveFPRn1BOm2ZDLzzhZ8qIeb2SlT64aHuukB75wO648a7HaYo/v7AdsrdhKT/13bgD2pp0TDZL5juDgrSE7OHxdzq1fU3GqLrrMY=,iv:7DTNX3LdTR4k1VzUJ4Dry7+UqTtubbR23f1Sh8fZs0g=,tag:t3FAkjryQSkbrtnhK9TbJQ==,type:str]
    mac_only_encrypted: true
    version: 3.13.3
