---
web:
  port: 80
storage:
  type: sqlite
  path: /config/sqlite.db
  caching: true
metrics: true
debug: false
ui:
  title: Status | Gatus
  header: Status
connectivity:
  checker:
    target: 1.1.1.1:53
    interval: 1m
endpoints:
  - name: flux-webhook
    group: external
    url: https://flux-webhook.${SECRET_DOMAIN}
    interval: 1m
    client:
      dns-resolver: tcp://1.1.1.1:53
    conditions:
      - "[STATUS] == 404"
    alerts:
      - type: custom
  - name: status
    group: guarded
    url: 1.1.1.1
    interval: 1m
    dns:
      query-name: "status.${CLUSTER_DOMAIN}"
      query-type: A
    conditions:
      - "len([BODY]) == 0"
    alerts:
      - type: custom
  - name: internal_alertmanager-heartbeat
    group: internal
    url: http://127.0.0.1/healthz
    interval: 1m
    conditions:
      - "[STATUS] == 200"
alerting:
  # discord:
  #   webhook-url: ${SECRET_DISCORD_GATUS_WH_URL}
  #   default-alert:
  #     enabled: true
  #     description: "healthcheck failed"
  #     send-on-resolved: true
  #     failure-threshold: 5
  #     success-threshold: 1
  custom:
    url: https://n8n-webhook.cftollefsen.com/webhook/gatus
    method: POST
    headers:
      Content-Type: application/json
    body: |
      {
        "endpoint_name": "[ENDPOINT_NAME]",
        "group": "[ENDPOINT_GROUP]", 
        "alert_state": "[ALERT_TRIGGERED_OR_RESOLVED]",
        "description": "[ALERT_DESCRIPTION]"
      }
    default-alert:
      description: health-check failed
      send-on-resolved: true
      failure-threshold: 3
      success-threshold: 3
  pushover:
    title: Gatus (Kubernetes)
    application-token: ${PUSHOVER_TOKEN}
    user-key: ${PUSHOVER_USER_KEY}
    priority: 1
    default-alert:
      description: health-check failed
      send-on-resolved: true
      failure-threshold: 3
      success-threshold: 3