---
# yaml-language-server: $schema=https://json.schemastore.org/kustomization
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: ceph-csi-cephfs
components:
  - ../../components/common
resources:
  - ./csi-cephfs/ks.yaml
