---
# yaml-language-server: $schema=https://crd.movishell.pl/external-secrets.io/externalsecret_v1beta1.json
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: &name recommendarr
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: onepassword
  target:
    name: recommendarr-secret
    template:
      engineVersion: v2
      data:
        SESSION_SECRET: "{{ .RECOMMENDARR_SESSION_SECRET }}"

        CUSTOM_OAUTH_AUTH_URL: "{{ .RECOMMENDARR_OAUTH_AUTH_URL }}"
        CUSTOM_OAUTH_TOKEN_URL: "{{ .RECOMMENDARR_OAUTH_TOKEN_URL }}"
        CUSTOM_OAUTH_USERINFO_URL: "{{ .RECOMMENDARR_OAUTH_USERINFO_URL }}"
        CUSTOM_OAUTH_CLIENT_ID: "{{ .RECOMMENDARR_OAUTH_CLIENT_ID }}"
        CUSTOM_OAUTH_CLIENT_SECRET: "{{ .RECOMMENDARR_OAUTH_CLIENT_SECRET }}"
        CUSTOM_OAUTH_SCOPE: "{{ .RECOMMENDARR_OAUTH_SCOPE }}"

  dataFrom:
    - extract:
        key: recommendarr