---
# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/external-secrets.io/externalsecret_v1.json
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: qbtools-private
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: onepassword
  target:
    name: qbtools-private-secret
    template:
      data:
        SABNZBD_API_KEY: "{{ .SABNZBD_API_KEY }}"
        QBITTORRENT_USERNAME: "{{ .QBT_WEBUI_USERNAME }}"
        QBITTORRENT_PASSWORD: "{{ .QBT_WEBUI_PASSWORD }}"
  dataFrom:
    - extract:
        key: sabnzbd
    - extract:
        key: qbittorrent
---
# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/external-secrets.io/externalsecret_v1.json
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: qbtools-private-config
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: onepassword
  target:
    name: qbtools-private-config-secret
    template:
      data:
        config.yaml: "{{ .QBTOOLS_PRIVATE_CONFIG }}"
  dataFrom:
    - extract:
        key: qbittorrent
