apiVersion: v1
kind: Secret
metadata:
  name: qbtools-private-config-secret
  namespace: media
type: Opaque
stringData:
  config.yaml: ENC[AES256_GCM,data:Vvr60YM1G2OzzxhdrocogEZ5r2zGi8UrlmQtnvO5KD51OG1iv2P2jOPHPx6HSWLKwDqRde81KnXpu3sPWXfMtMMFJvd3yNn9DcGQbVcOJGXm4HqHsNM6VusOZsMCsjLVDQgEX5hDN5f7z9Zr3DwUFLE61aJuF7Q9+hgsyMeAE0gzFxdvEL9a1/Qd29twgU6i6nY+7Azvmp11hx2FHvk/1QRA,iv:vlKyTCDu9vUPWwh4XW2QVcaS3xmqzgvvD91c0NI5qRA=,tag:q7As/6nx1cSfMkhm6ULHeQ==,type:str]
sops:
  age:
    - recipient: age1am64psa3hmwqnc924p9vuphyp4txekclpsysx6fkqtktgzppgusqfah833
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBwZ1dpQW5rbmVZQlF5dTZ6
        RmI5U1lCelJpanVpR3BtbDdmSXowNlpBK1Q0CnFMZjQyVkZaQSs5VXQzWUJ2OFA1
        MjlwRktXL2t4VDk5VW9aQ2tkL1MyUFUKLS0tIGs4M24yUFpKWDVzRjRjQWh6UXdL
        T2NDclBZc3JlbFA1aVF1MTZjbitDOG8KAwv9MmhV5UI/197Y5ZXBw/KqDsmKMyAG
        vzneZb/a+/83AjZYonP4Vh0vdo3GL/oJGWA3/OLjblBoQkugAbihwg==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2025-06-27T11:21:29Z"
  mac: ENC[AES256_GCM,data:QZWMI8auVvlIwHUypCLZ6R1/QhAk3tTrAjHRZ1xoehbMVznzM3GyFs/tSujwrCNX4Wm4suT9EDiYnZW4XnYYo8zoplW6XicqKYfXwASt8wmPJ1QjxhoaQ6XrUOXAz4+3BuG1a5PNL50kyQT1bFYu4eedICqnp3QBn6Wi6pFv4cI=,iv:qEs8hfNXgUEaiiCq2XBA0TMmA9sHOs9ox5srUE29GsM=,tag:ZuHQVFFY72lV47tn+rsgPw==,type:str]
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.10.2
