---
# yaml-language-server: $schema=https://crd.movishell.pl/external-secrets.io/externalsecret_v1.json
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: plex
  namespace: media
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: onepassword
  target:
    name: plex-secret
    creationPolicy: Owner
    template:
      data:
        #Plex
        PLEX_SECRET: "{{ .PLEX_SECRET }}"
        PLEX_TOKEN: "{{ .PLEX_TOKEN }}"

        #Restic backup
        RESTIC_REPOSITORY: "/repository/plex"
        RESTIC_PASSWORD: "{{ .RESTIC_PASSWORD }}"
  dataFrom:
    - extract:
        key: plex
    - extract:
        key: restic