---
# yaml-language-server: $schema=https://crd.movishell.pl/external-secrets.io/externalsecret_v1.json
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: plex
  namespace: media
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: onepassword
  target:
    name: plex-secret
    creationPolicy: Owner
    template:
      data:
        RESTIC_REPOSITORY: "nfs:nas.${SECRET_DOMAIN}:/mnt/truenas/cf-nas/backup/plex"
        RESTIC_PASSWORD: "{{ .RESTIC_PASSWORD }}"
        PLEX_SECRET: "{{ .PLEX_SECRET }}"
  dataFrom:
    - extract:
        key: restic
    - extract:
        key: plex