---
# yaml-language-server: $schema=https://raw.githubusercontent.com/bjw-s-labs/helm-charts/main/charts/other/app-template/schemas/helmrelease-helm-v2.schema.json
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: plex
  namespace: media
spec:
  interval: 1h
  chartRef:
    kind: OCIRepository
    name: app-template
    namespace: flux-system
# spec:
#   chart:
#     spec:
#       chart: app-template
#       version: 4.0.1
#       sourceRef:
#         kind: HelmRepository
#         name: bjw-s-labs
#         namespace: flux-system
#   interval: 30m
  install:
    remediation:
      retries: -1
  upgrade:
    cleanupOnFail: true
    remediation:
      retries: -1
  values:
    controllers:
      plex:
        annotations:
          reloader.stakater.com/auto: "true"
        containers:
          app:
            image:
              repository: ghcr.io/home-operations/plex
              tag: 1.41.7.9823@sha256:86e83ad4b671c4326e4f2b4520aced967c60efdf1aaa77191aad6d2ee4148d59
            env:
              TZ: ${SECRET_TIMEZONE}
              PLEX_ADVERTISE_URL: https://plex.${SECRET_DOMAIN}, 10.0.30.70:32400
              PLEX_NO_AUTH_NETWORKS: 10.0.10.0/24, 10.0.20.0/24, 10.0.30.0/24
            envFrom:
              - secretRef:
                  name: plex-secret
            probes:
              liveness: &probes
                enabled: true
                custom: true
                spec:
                  httpGet:
                    path: /identity
                    port: &port 32400
                  initialDelaySeconds: 0
                  periodSeconds: 10
                  timeoutSeconds: 1
                  failureThreshold: 3
              readiness: *probes
              startup:
                enabled: true
                spec:
                  failureThreshold: 30
                  periodSeconds: 10
            securityContext:
              allowPrivilegeEscalation: false
              readOnlyRootFilesystem: true
              capabilities: { drop: ["ALL"] }
            resources:
              requests:
                cpu: 100m
              limits:
                gpu.intel.com/i915: 1
                memory: 10Gi
    defaultPodOptions:
      securityContext:
        runAsNonRoot: true
        runAsUser: 1000
        runAsGroup: 1000
        fsGroup: 1000
        fsGroupChangePolicy: Always
        supplementalGroups: [44]
    service:
      app:
        controller: plex
        type: LoadBalancer
        annotations:
          lbipam.cilium.io/ips: 10.0.30.70
        ports:
          http:
            port: 32400
    ingress:
      app:
        enabled: true
        className: external
        annotations:
          # Extended timeouts for Plex streaming
          nginx.ingress.kubernetes.io/proxy-read-timeout: "3600"
          nginx.ingress.kubernetes.io/proxy-send-timeout: "3600"
          external-dns.alpha.kubernetes.io/target: "external.${SECRET_DOMAIN}"
        hosts:
          - host: &host plex.${SECRET_DOMAIN}
            paths:
              - path: /
                # pathType: Prefix
                service:
                  identifier: app
                  port: http
        tls:
          - hosts:
            - *host
    persistence:
      config:
        existingClaim: plex
      config-cache:
        existingClaim: plex-cache
        globalMounts:
          - path: /config/Library/Application Support/Plex Media Server/Cache
      media:
        type: nfs
        server: nas.${SECRET_DOMAIN}
        path: /mnt/truenas/cf-nas/data/media
        globalMounts:
          - path: /media
            readOnly: false
      tmpfs:
        type: emptyDir
        advancedMounts:
          plex:
            app:
              - path: /config/Library/Application Support/Plex Media Server/Logs
                subPath: logs
              - path: /transcode
                subPath: transcode
              - path: /tmp
                subPath: tmp
