---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: plex-cache
  namespace: media
spec:
  accessModes: ["ReadWriteOnce"]
  volumeMode: Filesystem
  resources:
    requests:
      storage: 50Gi
  storageClassName: csi-rbd-sc
