---
# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/kustomize.toolkit.fluxcd.io/kustomization_v1.json
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: &appname karakeep
  namespace: &namespace default
spec:
  targetNamespace: *namespace
  commonMetadata:
    labels:
      app.kubernetes.io/name: *appname
  interval: 30m
  timeout: 5m
  path: "./kubernetes/apps/default/karakeep/app"
  prune: true
  sourceRef:
    kind: GitRepository
    name: flux-system
    namespace: flux-system
  wait: false
  dependsOn:
    - name: ceph-csi-rbd
      namespace: ceph-csi-rbd
    - name: external-secrets
      namespace: external-secrets
  components:
    - ../../../../components/gatus/external
    - ../../../../components/ceph-rbd
  postBuild:
    substitute:
      APP: *app
      CEPH_RBD_CAPACITY: 2Gi
    substituteFrom:
      - name: cluster-secrets
        kind: Secret
