---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - externalsecret.yaml
  - helmrelease.yaml
  - tempo-otlp-external-service.yaml
  - tempo-otlp-http-external-service.yaml