---
# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/external-secrets.io/externalsecret_v1.json
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: mariadb-operator-secret
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: onepassword
  target:
    name: mariadb-operator-secret
    template:
      engineVersion: v2
      data:
        mariadb-root-password: "{{ .MARIADB_ROOT_PASSWORD }}"
        booklore-username: "{{ .BOOKLORE_DB_USER }}"
        booklore-password: "{{ .BOOKLORE_DB_PASS }}"
  dataFrom:
    - extract:
        key: mariadb
    - extract:
        key: booklore
