---
# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/external-secrets.io/externalsecret_v1.json
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: mydia
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: onepassword
  target:
    name: mydia-secret
    creationPolicy: Owner
    template:
      engineVersion: v2
      data:
        # Mydia
        POSTGRES_USER: &dbUser "{{ .MYDIA_POSTGRES_USER }}"
        POSTGRES_PASSWORD: &dbPass "{{ .MYDIA_POSTGRES_PASS }}"
        POSTGRES_DB: &dbName mydia

        SECRET_KEY_BASE: "{{ .MYDIA_SECRET_KEY_BASE }}" # Required: generate with openssl rand -base64 48
        GUARDIAN_SECRET_KEY: "{{ .MYDIA_GUARDIAN_SECRET_KEY }}" # Required: generate with openssl rand -base64 48

        DATABASE_TYPE: postgres
        DATABASE_HOST: &dbHost "{{ .POSTGRES_RW_SVC }}"
        DATABASE_PORT: "5432"
        DATABASE_NAME: *dbName
        DATABASE_USER: *dbName
        DATABASE_PASSWORD: *dbPass

        INIT_POSTGRES_DBNAME: *dbName
        INIT_POSTGRES_HOST: *dbHost
        INIT_POSTGRES_USER: *dbUser
        INIT_POSTGRES_PASS: *dbPass
        INIT_POSTGRES_SUPER_PASS: "{{ .POSTGRES_SUPER_PASS }}"

        #Restic backup
        RESTIC_REPOSITORY: "/repository/mydia"
        RESTIC_PASSWORD: "{{ .RESTIC_PASSWORD }}"
  dataFrom:
    - extract:
        key: cloudnative-pg
    - extract:
        key: mydia
    - extract:
        key: restic
