---
apiVersion: postgresql.cnpg.io/v1
kind: Cluster
metadata:
  name: reptile-tracker-postgres
spec:
  instances: 3

  imageName: ghcr.io/cloudnative-pg/postgresql:16.6

  primaryUpdateStrategy: unsupervised

  storage:
    size: 10Gi
    storageClass: ceph-block

  postgresql:
    parameters:
      max_connections: "200"
      shared_buffers: 256MB
      effective_cache_size: 1GB
      maintenance_work_mem: 64MB
      checkpoint_completion_target: "0.9"
      wal_buffers: 16MB
      default_statistics_target: "100"
      random_page_cost: "1.1"
      effective_io_concurrency: "200"
      work_mem: 5MB
      min_wal_size: 1GB
      max_wal_size: 4GB

  monitoring:
    enablePodMonitor: true

  backup:
    retentionPolicy: 14d
    barmanObjectStore:
      destinationPath: s3://cnpg-backups/reptile-tracker
      endpointURL: http://minio.storage.svc.cluster.local:9000
      s3Credentials:
        accessKeyId:
          name: reptile-tracker-postgres-s3-secret
          key: ACCESS_KEY_ID
        secretAccessKey:
          name: reptile-tracker-postgres-s3-secret
          key: ACCESS_SECRET_KEY
      wal:
        compression: gzip
      data:
        compression: gzip
        immediateCheckpoint: true
        jobs: 2

  bootstrap:
    initdb:
      database: reptile_tracker
      owner: reptile_tracker
      secret:
        name: reptile-tracker-postgres-user
