# This file should be encrypted with SOPS before committing
---
apiVersion: v1
kind: Secret
metadata:
  name: reptile-tracker-postgres-user
type: kubernetes.io/basic-auth
stringData:
  username: reptile_tracker
  password: "CHANGE_ME_GENERATE_SECURE_PASSWORD"
---
apiVersion: v1
kind: Secret
metadata:
  name: reptile-tracker-postgres-s3-secret
type: Opaque
stringData:
  ACCESS_KEY_ID: "CHANGE_ME"
  ACCESS_SECRET_KEY: "CHANGE_ME"
