---
# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/kustomize.toolkit.fluxcd.io/kustomization_v1.json
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: &app readmeabook
  namespace: &namespace media
spec:
  commonMetadata:
    labels:
      app.kubernetes.io/name: readmeabook
  components:
    - ../../../../components/ceph-rbd
    - ../../../../components/gatus/guarded
    # - ../../../../components/proxy-application
    # - ../../../../components/ext-auth
  dependsOn:
    - name: cloudnative-pg-cluster-v17
      namespace: database
    - name: dragonfly-cluster
      namespace: database
  interval: 1h
  path: "./kubernetes/apps/media/readmeabook/app"
  postBuild:
    substitute:
      APP: *app
      # EXT_AUTH_PORT: "8084"
      # GROUP: Media
      # SUBDOMAIN: *app
      # DESCRIPTION: Book and audiobook downloader
      CEPH_RBD_CAPACITY: 2Gi
      # PROXY_ADMIN_GROUP: media-admins
    substituteFrom:
      - name: cluster-secrets
        kind: Secret
  prune: true
  sourceRef:
    kind: GitRepository
    name: flux-system
    namespace: flux-system
  targetNamespace: *namespace
  timeout: 5m
  wait: false