---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: &app dragonfly-operator
  namespace: database
# spec:
#   interval: 1h
#   chartRef:
#     kind: OCIRepository
#     name: app-template
#     namespace: flux-system
# spec:
#   interval: 30m
#   chart:
#     spec:
#       chart: app-template
#       version: 4.0.1
#       sourceRef:
#         kind: HelmRepository
#         name: bjw-s
#         namespace: flux-system
spec:
  interval: 15m
  chart:
    spec:
      chart: dragonfly-operator
      version: 1.1.11 # The version from your OCI source
      sourceRef:
        kind: OCIRepository
        name: dragonfly-operator # The OCI source you already have
        namespace: flux-system
  install:
    crds: CreateReplace
    remediation:
      retries: -1
  upgrade:
    crds: CreateReplace
    cleanupOnFail: true
    remediation:
      retries: -1
  values:
    controllers:
      dragonfly-operator:
        serviceAccount:
          identifier: *app
        containers:
          app:
            image:
              repository: docker.dragonflydb.io/dragonflydb/operator
              tag: v1.1.11@sha256:11cef45ec1079b9d97930fc99ecd08ba29d4eca55cdb45887cb0ac40ee4e4d24
            args:
              - "--health-probe-bind-address=:8081"
              - "--metrics-bind-address=127.0.0.1:8080"
            command:
              - "/manager"
            securityContext:
              allowPrivilegeEscalation: false
              readOnlyRootFilesystem: true
              capabilities: { drop: ["ALL"] }
            probes:
              liveness:
                enabled: true
                custom: true
                spec:
                  httpGet:
                    path: /healthz
                    port: &port 8081
                  initialDelaySeconds: 15
                  periodSeconds: 20
                  timeoutSeconds: 1
                  failureThreshold: 3
              readiness:
                enabled: true
                custom: true
                spec:
                  httpGet:
                    path: /readyz
                    port: *port
                  initialDelaySeconds: 5
                  periodSeconds: 10
                  timeoutSeconds: 1
                  failureThreshold: 3
              startup:
                enabled: false
            resources:
              requests:
                cpu: 10m
                memory: 64Mi
              limits:
                cpu: 500m
                memory: 128Mi
        pod:
          topologySpreadConstraints:
            - maxSkew: 1
              topologyKey: kubernetes.io/hostname
              whenUnsatisfiable: DoNotSchedule
              labelSelector:
                matchLabels:
                  app.kubernetes.io/name: *app
    service:
      app:
        controller: *app
        ports:
          http:
            port: *port

    serviceAccount:
      dragonfly-operator: {}

    # serviceMonitor:
    #   app:
    #     serviceName: *app
    #     endpoints:
    #       - port: metrics
    #         scheme: http
    #         path: /metrics
    #         interval: 1m
    #         scrapeTimeout: 10s