---
# yaml-language-server: $schema=https://crd.movishell.pl/external-secrets.io/externalsecret_v1beta1.json
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: &name mealie
  namespace: default
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: onepassword
  target:
    name: *name
    template:
      engineVersion: v2
      data:
        POSTGRES_USER: &dbuser "{{ .POSTGRES_USER }}"
        POSTGRES_PASSWORD: &dbpass "{{ .POSTGRES_PASS }}"
        POSTGRES_SERVER: &dbserver "{{ .POSTGRES_RW_SVC }}"
        POSTGRES_PORT: "5432"
        POSTGRES_DB: &dbname ${APP}
        DB_ENGINE: "postgres"
        
        INIT_POSTGRES_DBNAME: *dbname
        INIT_POSTGRES_HOST: *dbserver
        INIT_POSTGRES_USER: *dbuser
        INIT_POSTGRES_PASS: *dbpass
        INIT_POSTGRES_SUPER_PASS: "{{ .POSTGRES_SUPER_PASS }}"
        # Base Values
        BASE_URL: https://mealie.${SECRET_DOMAIN}
        ALLOW_SIGNUP: "false"
        AUTO_BACKUP_ENABLED: "true"
        API_DOCS: "false"
        TZ: ${SECRET_TIMEZONE}
        WORKERS_PER_CORE: "1"
        MAX_WORKERS: "1"
        WEB_CONCURRENCY: "1"
        
        # OpenAI Configuration
        OPENAI_API_KEY: "{{ .OPENAI_API_KEY }}"
        OPENAI_BASE_URL: "https://api.openai.com/v1"
        OPENAI_MODEL: "gpt-3.5-turbo"
        
        # OIDC Configuration
        OIDC_AUTH_ENABLED: "true"
        OIDC_PROVIDER_NAME: "authentik"
        OIDC_SIGNUP_ENABLED: "false"
        OIDC_USER_GROUP: "{{ .MEALIE_OIDC_USER_GROUP }}"
        OIDC_ADMIN_GROUP: "{{ .MEALIE_OIDC_ADMIN_GROUP }}"
        OIDC_AUTO_REDIRECT: "true"
        OIDC_CONFIGURATION_URL: "{{ .MEALIE_OIDC_CONFIGURATION_URL }}"
        OIDC_CLIENT_ID: "{{ .MEALIE_OIDC_CLIENT_ID }}"
        OIDC_CLIENT_SECRET: "{{ .MEALIE_OIDC_CLIENT_SECRET }}"
        OIDC_REMEMBER_ME: "true"

  dataFrom:
    - extract:
        key: mealie
    - extract:
        key: cloudnative-pg
    - extract:
        key: openai