---
apiVersion: v1
kind: ConfigMap
metadata:
  name: homepage-config
  namespace: default
data:
  bookmarks.yaml: |
    - Media:
        - YouTube:
            - href: https://youtube.com/feed/subscriptions
    - Tech:
        - HackerNews:
            - href: https://news.ycombinator.com
        - Moronix:
            - href: https://www.phoronix.com
    - Social:
        - Reddit:
            - href: https://reddit.com
  docker.yaml: ""
  kubernetes.yaml: |
    mode: cluster
    ingress: true
  services.yaml: |
    # - Calendar:
    #     - Agenda:
    #         widget:
    #           type: calendar
    #           view: agenda # optional - possible values monthly, agenda
    #           maxEvents: 20 # optional - defaults to 10
    #           integrations: # optional
    #             - type: sonarr # active widget type that is currently enabled on homepage - possible values: radarr, sonarr>
    #               service_group: Downloads # group name where widget exists
    #               service_name: Sonarr # service name for that widget
    #             - type: radarr # active widget type that is currently enabled on homepage - possible values: radarr, sonarr>
    #               service_group: Downloads # group name where widget exists
    #               service_name: Radarr # service name for that widget
    - Infrastructure:
        - TrueNAS:
            href: https://nas.${SECRET_DOMAIN}
            icon: truenas.png
            widget:
              type: truenas
              fields: []
              url: https://nas.${SECRET_DOMAIN}
              key: {{HOMEPAGE_VAR_TRUENAS_TOKEN}}
              enablePools: true
        - OPNSense:
            href: http://10.0.30.1
            icon: opnsense.png
            widget:
              type: opnsense
              url: http://10.0.30.1
              username: {{HOMEPAGE_VAR_OPNSENSE_API_KEY}}
              password: {{HOMEPAGE_VAR_OPNSENSE_API_SECRET}}
              wan: igc3
    - Media:
      - Plex:
          icon: plex.png
          href: https://plex.${SECRET_DOMAIN}
          description: Media Server
          widget:
            type: plex
            url: http://plex.media.svc.cluster.local:32400
            key: {{HOMEPAGE_VAR_PLEX_KEY}}
            enableNowPlaying: true
      - Jellyseer:
          icon: jellyseer.png
          href: https://request.${SECRET_DOMAIN}
          description: Media Requests
          widget:
            type: jellyseerr
            url: http://jellyseerr.media.svc.cluster.local
            key: {{HOMEPAGE_VAR_JELLYSEER_KEY}}
      - qBittorrent:
          icon: qbittorrent.png
          href: https://qbittorrent.${SECRET_DOMAIN}
          description: Torrent Management
          widget:
            type: qbittorrent
            url: http://qbittorrent-app.media.svc.cluster.local
            username: {{HOMEPAGE_VAR_QBITTORRENT_USERNAME}}
            password: {{HOMEPAGE_VAR_QBITTORRENT_PASSWORD}}
      - Radarr:
          icon: radarr.png
          href: https://radarr.${SECRET_DOMAIN}
          description: Movies Management
          widget:
            type: radarr
            url: http://radarr.media.svc.cluster.local:7878
            key: {{HOMEPAGE_VAR_RADARR_KEY}}
      - Sonarr:
          icon: sonarr.png
          href: https://sonarr.${SECRET_DOMAIN}
          description: TV Shows Management
          widget:
            type: sonarr
            url: http://sonarr.media.svc.cluster.local:80
            key: {{HOMEPAGE_VAR_SONARR_KEY}}
      - Bazarr:
          icon: bazarr.png
          href: https://bazarr.${SECRET_DOMAIN}
          description: Subtitles Management
          widget:
            type: bazarr
            url: http://bazarr.media.svc.cluster.local:6767
            key: {{HOMEPAGE_VAR_BAZARR_KEY}}
    - Favorites:
        - home-cluster:
            icon: si-github
            href: https://github.com/chrtol/home-cluster
            description: My Code Repository
  settings.yaml: |
    title: Dashboard
    background: https://images.unsplash.com/photo-1502790671504-542ad42d5189?auto=format&fit=crop&w=2560&q=80
    theme: dark
    color: slate
    headerStyle: boxed
    layout:
      Calendar:
        style: columns
      Automation:
        style: columns
      Selfhosted:
        style: row
        columns: 2
      Downloads:
        style: row
        columns: 3
      Games:
        style: row
      Infrastructure:
        style: row
        columns: 2
      Monitoring:
        style: row
        columns: 3
  widgets.yaml: |
    - resources:
        backend: kubernetes
        cpu: true
        expanded: true
        memory: true
    - search:
        provider: [brave, bing]
        focus: false
        target: _blank
    - kubernetes:
        cluster:
          cpu: true
          memory: true
          show: true
          showLabel: true
        nodes:
          cpu: true
          memory: true
          show: false
          showLabel: true
    - openmeteo:
        label: Home
        units: metric
        cache: 5
    - datetime:
        text_size: l
        format:
          dateStyle: long
          timeStyle: short
          hourCycle: h23
    - jellyseerr:
      type: jellyseerr
      url: http://jellyseerr.host.or.ip
      key: apikeyapikeyapikeyapikeyapikey


