---
# yaml-language-server: $schema=https://kubernetes-schemas.ok8.sh/kustomize.toolkit.fluxcd.io/kustomization_v1.json
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: &app glance
  namespace: &namespace default
spec:
  targetNamespace: *namespace
  commonMetadata:
    labels:
      app.kubernetes.io/name: *app
  components:
    - ../../../../components/ext-auth
  postBuild:
    substitute:
      APP: *app
      EXT_AUTH_PORT: "8080"
      EXT_AUTH_GATEWAY: external
      EXT_AUTH_DNS_TARGET: external.${SECRET_DOMAIN}
    substituteFrom:
      - name: cluster-secrets
        kind: Secret
      - name: glance-secret
        kind: Secret
  path: ./kubernetes/apps/default/glance/app
  prune: true
  sourceRef:
    kind: GitRepository
    name: flux-system
    namespace: flux-system
  wait: false
  interval: 30m
  retryInterval: 1m
  timeout: 5m