{
 "title": "SMARTctl Exporter Dashboard",
 "description": "Extended smartctl-exporter Dashboard",
 "tags": [
  "prometheus",
  "node_exporter",
  "smartmon"
 ],
 "time": { "from": "now-1h", "to": "now" },
 "refresh": "1m",
 "templating": {
  "list": [
   {
    "name": "node",
    "query": {
     "query": "label_values(smartctl_device,node)"
    }
   },
   {
    "name": "disk",
    "query": {
     "query": "label_values(smartctl_device,device)"
    }
   },
   {
    "name": "type",
    "query": {
     "query": "label_values(smartctl_device,interface)"
    }
   },
   {
    "name": "device_model",
    "query": {
     "query": "label_values(smartctl_device,model_name)"
    }
   },
   {
    "name": "serial_number",
    "query": {
     "query": "label_values(smartctl_device,serial_number)"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "Disk Inventory",
   "type": "table",
   "gridPos": { "x": 0, "y": 0, "w": 24, "h": 6 },
   "targets": [
    {
     "legendFormat": "__auto",
     "expr": "smartctl_device{job=\"smartctl\", node=~\"$node\", device=~\"$disk\", interface=~\"$type\", serial_number=~\"$serial_number\", model_name=~\"$device_model\"}"
    }
   ]
  },
  {
   "title": "Disk Temperature",
   "type": "timeseries",
   "gridPos": { "x": 0, "y": 6, "w": 10, "h": 9 },
   "fieldConfig": { "defaults": { "unit": "celsius" } },
   "targets": [
    {
     "expr": "avg(smartctl_device_temperature{node=~\"$node\", device=~\"$disk\"} * on(instance, device) group_left(interface,serial_number,model_name) smartctl_device{interface=~\"$type\",serial_number=~\"$serial_number\",model_name=~\"$device_model\"}) by (node,device)",
     "legendFormat": "{{node}} {{device}}"
    }
   ]
  },
  {
   "title": "Devices",
   "type": "stat",
   "gridPos": { "x": 18, "y": 6, "w": 2, "h": 4 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(smartctl_device{node=~\"$node\", device=~\"$disk\", interface=~\"$type\",serial_number=~\"$serial_number\",model_name=~\"$device_model\"})"
    }
   ]
  },
  {
   "title": "Disk Interfaces",
   "type": "piechart",
   "gridPos": { "x": 18, "y": 10, "w": 6, "h": 5 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "label_replace(label_replace(sum(smartctl_device{job=\"smartctl\", node=~\"$node\", device=~\"$disk\"}) by (interface),\"interface\",\"SATA\",\"interface\",\"sat\"),\"interface\",\"NVMe\",\"interface\",\"nvme\")",
     "legendFormat": "{{interface}}"
    }
   ]
  },
  {
   "title": "Media Errors",
   "type": "timeseries",
   "gridPos": { "x": 10, "y": 6, "w": 8, "h": 4 },
   "targets": [
    {
     "expr": "smartctl_device_media_errors{node=~\"$node\", device=~\"$disk\"} * on(instance, device) group_left(interface,serial_number,model_family,model_name) smartctl_device{interface=~\"$type\",serial_number=~\"$serial_number\",model_name=~\"$device_model\"} > 0",
     "legendFormat": "{{node}} {{device}}"
    }
   ]
  },
  {
   "title": "Unhealthy",
   "type": "stat",
   "gridPos": { "x": 20, "y": 6, "w": 2, "h": 4 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "count(count by (node, device) ((smartctl_device_smart_status{job=\"smartctl\", node=~\"$node\", device=~\"$disk\"} == 0) or (smartctl_device_attribute{job=\"smartctl\", node=~\"$node\", device=~\"$disk\", attribute_id=\"177\", attribute_value_type=\"value\"} <= 10) or (smartctl_device_percentage_used{job=\"smartctl\", node=~\"$node\", device=~\"$disk\"} >= 90) or (smartctl_device_attribute{job=\"smartctl\", node=~\"$node\", device=~\"$disk\", attribute_id=~\"197|198\", attribute_value_type=\"raw\"} > 0))) or vector(0)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "NVMe Critical Warnings",
   "type": "timeseries",
   "gridPos": { "x": 10, "y": 10, "w": 8, "h": 5 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "smartctl_device_critical_warning{node=~\"$node\", device=~\"$disk\"} * on(instance, device) group_left(interface,serial_number,model_family,model_name) smartctl_device{interface=~\"$type\",serial_number=~\"$serial_number\",model_name=~\"$device_model\"} > 0",
     "legendFormat": "Critical Warnings {{node}} {{device}}"
    }
   ]
  },
  {
   "type": "stat",
   "gridPos": { "x": 22, "y": 6, "w": 2, "h": 4 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "count(count(smartctl_device{job=\"smartctl\"}) by (node))",
     "legendFormat": "nodes"
    }
   ]
  },
  {
   "title": "Disk Lifetime",
   "type": "table",
   "gridPos": { "x": 0, "y": 15, "w": 12, "h": 10 },
   "targets": [
    {
     "expr": "max(smartctl_device_power_on_seconds{node=~\"$node\", device=~\"$disk\"} * on(instance, device) group_left(interface,serial_number,model_family,model_name) smartctl_device{interface=~\"$type\",serial_number=~\"$serial_number\",model_name=~\"$device_model\"}) by (node, device)",
     "legendFormat": "__auto"
    },
    {
     "expr": "max(smartctl_device_power_cycle_count{node=~\"$node\", device=~\"$disk\"} * on(instance, device) group_left(interface,serial_number,model_family,model_name) smartctl_device{interface=~\"$type\",serial_number=~\"$serial_number\",model_name=~\"$device_model\"}) by (node, device)",
     "legendFormat": "Power Cycles"
    }
   ]
  },
  {
   "title": "Total Data Written on SSDs",
   "type": "table",
   "gridPos": { "x": 12, "y": 15, "w": 12, "h": 10 },
   "targets": [
    {
     "expr": "max(smartctl_device_bytes_written{node=~\"$node\", device=~\"$disk\"} * on(instance, device) group_left(interface,serial_number,model_family,model_name) smartctl_device{interface=~\"$type\",serial_number=~\"$serial_number\",model_name=~\"$device_model\"}) by (device, node)",
     "legendFormat": "__auto"
    },
    {
     "expr": "max((smartctl_device_attribute{node=~\"$node\", device=~\"$disk\", attribute_name=\"Total_LBAs_Written\", attribute_value_type=\"raw\"} * on (instance,device) smartctl_device_block_size{node=~\"$node\", device=~\"$disk\",blocks_type=\"physical\"}) * on(instance, device) group_left(interface,serial_number,model_family,model_name) smartctl_device{interface=~\"$type\",serial_number=~\"$serial_number\",model_name=~\"$device_model\"}) by (device, node)\n",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Wear Level on SATA Devices",
   "type": "gauge",
   "gridPos": { "x": 0, "y": 25, "w": 12, "h": 11 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "sort_desc(100 - smartctl_device_attribute{node=~\"$node\", device=~\"$disk\", attribute_name=\"Wear_Leveling_Count\",attribute_value_type=\"value\"} * on(instance, device) group_left(interface,serial_number,model_family,model_name) smartctl_device{interface=~\"sat\",serial_number=~\"$serial_number\",model_name=~\"$device_model\"})",
     "legendFormat": "{{node}} {{device}}"
    }
   ]
  },
  {
   "title": "Wear Level on NVMe Devices",
   "type": "gauge",
   "gridPos": { "x": 12, "y": 25, "w": 12, "h": 11 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "sort_desc(smartctl_device_percentage_used{node=~\"$node\", device=~\"$disk\"} * on(instance, device) group_left(interface,serial_number,model_family,model_name) smartctl_device{interface=~\"nvme\",serial_number=~\"$serial_number\",model_name=~\"$device_model\"})\n",
     "legendFormat": "{{node}} {{device}}"
    }
   ]
  }
 ]
}