---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: &app garage-webui
spec:
  interval: 1h
  chartRef:
    kind: OCIRepository
    name: app-template
    namespace: flux-system
  values:
    controllers:
      garage-webui:
        annotations:
          reloader.stakater.com/auto: "true"
        containers:
          app:
            image:
              repository: docker.io/khairul169/garage-webui
              tag: 1.0.9@sha256:c931455c25bfbededa450cd7ec6f389ce52ad1bc861f8d0b93d00ced78e438dd
            env:
              TZ: ${SECRET_TIMEZONE}
              API_BASE_URL: http://garage.database.svc.cluster.local:3903
              S3_ENDPOINT_URL: http://garage.database.svc.cluster.local:3900
              CONFIG_PATH: /etc/garage/config.toml
              API_ADMIN_KEY: ${SECRET_GARAGE_ADMIN_TOKEN}
            securityContext:
              allowPrivilegeEscalation: false
              readOnlyRootFilesystem: true
              capabilities: { drop: ["ALL"] }
            resources:
              requests:
                cpu: 5m
                memory: 50Mi
              limits:
                memory: 128Mi
    defaultPodOptions:
      securityContext:
        runAsNonRoot: true
        runAsUser: 1000
        runAsGroup: 1000
        fsGroup: 1000
        fsGroupChangePolicy: OnRootMismatch
    service:
      app:
        ports:
          http:
            port: &port 3909
    route:
      app:
        hostnames: ["garage.${SECRET_DOMAIN}"]
        parentRefs:
          - name: internal
            namespace: network
            sectionName: https
        rules:
          - backendRefs:
              - identifier: app
                port: *port
    persistence:
      config:
        type: configMap
        name: config.toml
        globalMounts:
          - path: /etc/garage/
            readOnly: true