---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: "${APP}"
spec:
  accessModes: ["${CEPH_RBD_ACCESSMODES:=ReadWriteOnce}"]
  resources:
    requests:
      storage: "${CEPH_RBD_CAPACITY:=1Gi}"
  storageClassName: "${CEPH_RBD_STORAGECLASS:=csi-rbd-sc}"