---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: "${CEPH_RBD_CLAIM_NAME}:=${APP}"
spec:
  accessModes: ["${CEPH_RBD_ACCESSMODES:=ReadWriteOnce}"]
  volumeMode: "${CEPH_RBD_VOLUMEMODE:=Filesystem}"
  resources:
    requests:
      storage: "${CEPH_RBD_CAPACITY:=1Gi}"
  storageClassName: "${CEPH_RBD_STORAGECLASS:=csi-rbd-sc}"