---
# yaml-language-server: $schema=https://raw.githubusercontent.com/fluxcd-community/flux2-schemas/main/helmrelease-helm-v2.json
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: proxmox-csi
  namespace: csi-proxmox
spec:
  interval: 30m
  chartRef:
    kind: OCIRepository
    name: proxmox-csi-plugin
    namespace: flux-system
  install:
    remediation:
      retries: 4
    timeout: 10m
  upgrade:
    cleanupOnFail: true
    remediation:
      retries: 4
    timeout: 10m
  values:
    config:
      clusters:
        - url: https://10.0.30.12:8006/api2/json
          insecure: false
          token_id: "kubernetes-csi@pve!kubernetes-csi"
          region: homelab # match proxmox cluster
          
    createNamespace: true
    # node:
    #   tolerations:
    #     - operator: Exists

    # # # Deploy Node CSI driver only on proxmox nodes
    # # nodeSelector:
    # #   node-role.kubernetes.io/control-plane: ""
    # # tolerations:
    # #   - key: node-role.kubernetes.io/control-plane
    # #     effect: NoSchedule

    # # TODO: look into https://github.com/sergelogvinov/proxmox-csi-plugin/blob/main/charts/proxmox-csi-plugin/values.yaml#L73 performance tweaks
    # # https://github.com/sergelogvinov/proxmox-csi-plugin/blob/2cae7bc8402b168a69a1d375309f837fdc7b70fb/docs/options.md
    storageClass:
      - name: proxmox
        storage: kube-fs
        cache: writethrough
        fstype: cephfs
        reclaimPolicy: Delete
        ssd: "true"
        provisioner: csi.proxmox.sinextra.dev
        allowVolumeExpansion: true
        annotations:
          storageclass.kubernetes.io/is-default-class: "true"
  valuesFrom:
    - targetPath: config.clusters[0].token_secret
      kind: Secret
      name: proxmox-csi
      valuesKey: proxmox-csi-token-secret
