---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: pv-ceph
spec:
  accessModes:
    - ReadWriteOnce
  capacity:
    storage: 10Gi
  csi:
    driver: csi.proxmox.sinextra.dev
    fsType: xfs
    volumeAttributes:
      storage: zfs
    volumeHandle: ceph/proxmox/zfs/kube-fs
  storageClassName: proxmox-zfs