---
# yaml-language-server: $schema=https://kubernetes-schemas.perry.cafe/external-secrets.io/externalsecret_v1beta1.json
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: opnsense-exporter-secret
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: onepassword
  target:
    deletionPolicy: Delete
    template:
      engineVersion: v2
      data:
        OPNSENSE_EXPORTER_OPS_API_KEY: "{{ .OPNSENSE_EXPORTER_API_KEY }}"
        OPNSENSE_EXPORTER_OPS_API_SECRET: "{{ .OPNSENSE_EXPORTER_API_SECRET }}"
  dataFrom:
    - extract:
        key: opnsense