---
# yaml-language-server: $schema=https://raw.githubusercontent.com/bjw-s-labs/helm-charts/main/charts/other/app-template/schemas/helmrelease-helm-v2.schema.json
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: &app opnsense-exporter
spec:
  interval: 1h
  chartRef:
    kind: OCIRepository
    name: app-template
    namespace: flux-system
  install:
    remediation:
      retries: -1
  upgrade:
    cleanupOnFail: true
    remediation:
      retries: 3
  values:
    controllers:
      opnsense-exporter:
        annotations:
          reloader.stakater.com/auto: "true"
        containers:
          app:
            image:
              repository: ghcr.io/athennamind/opnsense-exporter
              tag: 0.0.11
            args:
              # - --log.level=debug
              # - --log.format=json
              - --exporter.instance-label=gw
              - --web.listen-address=:8080
            env:
              OPNSENSE_EXPORTER_OPS_PROTOCOL: "https"
              OPNSENSE_EXPORTER_INSECURE: "true"
              TZ: ${SECRET_TIMEZONE}
            envFrom: &envFrom
              - secretRef:
                  name: opnsense-exporter-secret
            probes:
              liveness:
                enabled: true
              readiness:
                enabled: true
            resources: &resources
              requests:
                cpu: 10m
              limits:
                memory: 128Mi
            securityContext: &securityContext
              allowPrivilegeEscalation: false
              readOnlyRootFilesystem: true
              capabilities:
                drop:
                  - ALL
      check-firmware-update:
        type: cronjob
        cronjob:
          schedule: "@daily"
          failedJobsHistory: 1
          successfulJobsHistory: 0
          timeZone: ${SECRET_TIMEZONE}
        containers:
          app:
            image:
              repository: docker.io/alpine/curl
              tag: 8.14.1@sha256:e37808e50268ff935a924086856c22477e9754bcd90da9bc5bf131ac9612356a
            command:
              - /bin/sh
              - -c
            args:
              - >-
                curl --fail --silent --show-error --location --insecure --request POST
                --user "$OPNSENSE_EXPORTER_OPS_API_KEY:$OPNSENSE_EXPORTER_OPS_API_SECRET"
                --data "{}"
                "https://opnsense.${SECRET_DOMAIN}/api/core/firmware/status"
            envFrom: *envFrom
            resources: *resources
            securityContext: *securityContext
    defaultPodOptions:
      securityContext:
        runAsNonRoot: true
        runAsUser: 568
        runAsGroup: 568
    service:
      app:
        controller: *app
        ports:
          http:
            port: 8080
    serviceMonitor:
      app:
        serviceName: *app
        endpoints:
          - port: http
            scheme: http
            path: /metrics
            interval: 1m
            scrapeTimeout: 10s
