---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: restic-unlock
  namespace: volsync-system
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: onepassword
  target:
    name: restic-unlock-secret
    creationPolicy: Owner
    template:
      engineVersion: v2
      data:
        RESTIC_PASSWORD: "{{ .RESTIC_PASSWORD }}"
  dataFrom:
    - extract:
        key: restic
