---
# yaml-language-server: $schema=https://raw.githubusercontent.com/bjw-s/helm-charts/main/charts/other/app-template/schemas/helmrelease-helm-v2.schema.json
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: lldap
spec:
  interval: 1h
  timeout: 5m
  chartRef:
    kind: OCIRepository
    name: app-template
    namespace: flux-system
  install:
    createNamespace: true
    remediation:
      retries: 5
  upgrade:
    remediation:
      retries: 5
  values:
    controllers:
      lldap:
        containers:
          main:
            image:
              repository: ghcr.io/lldap/lldap
              tag: v0.6.1
            probes:
              startup:
                enabled: true
                spec:
                  failureThreshold: 30
                  periodSeconds: 5
              liveness:
                enabled: true
              readiness:
                enabled: true
            envFrom:
              - secretRef:
                  name: lldap-secret
            env:
              UID: "568"
              GID: "568"
    service:
      main:
        controller: lldap
        ports:
          http:
            port: 3890
          web:
            enabled: true
            protocol: TCP
            port: 17170
    ingress:
      main:
        enabled: true
        className: internal
        annotations:
          internal-dns.alpha.kubernetes.io/target: "internal.${SECRET_DOMAIN}"
        hosts:
          - host: &host ldap.${SECRET_DOMAIN}
            paths:
              - path: /
                pathType: Prefix
                service:
                  identifier: main
                  port: web
        tls:
          - hosts:
              - *host
    persistence:
      config:
        enabled: true
        existingClaim: lldap
        globalMounts:
          - path: /data
