---
apiVersion: gateway.envoyproxy.io/v1alpha1
kind: EnvoyProxy
metadata:
  name: envoy-internal-proxy
  namespace: network
spec:
  telemetry:
    tracing:
      samplingRate: 50
      provider:
        type: OpenTelemetry
        host: tempo-distributor.observability.svc.cluster.local
        port: 4317
  provider:
    type: Kubernetes
    kubernetes:
      envoyDeployment:
        name: envoy-gateway-internal
        replicas: 3
        pod:
          affinity:
            podAntiAffinity:
              preferredDuringSchedulingIgnoredDuringExecution:
                - weight: 100
                  podAffinityTerm:
                    labelSelector:
                      matchLabels:
                        gateway.envoyproxy.io/owning-gateway-name: internal
                    topologyKey: kubernetes.io/hostname
      envoyService:
        name: envoy-gateway-internal
        type: LoadBalancer
        externalTrafficPolicy: Local
        loadBalancerIP: "10.0.30.43"
